//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public class Animation : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Animation(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Animation obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Animation obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Animation() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AssimpPINVOKE.delete_Animation(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public String Name {
    set {
      AssimpPINVOKE.Animation_Name_set(swigCPtr, String.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Animation_Name_get(swigCPtr);
      String ret = (cPtr == global::System.IntPtr.Zero) ? null : new String(cPtr, false);
      return ret;
    } 
  }

  public double Duration {
    set {
      AssimpPINVOKE.Animation_Duration_set(swigCPtr, value);
    } 
    get {
      double ret = AssimpPINVOKE.Animation_Duration_get(swigCPtr);
      return ret;
    } 
  }

  public double TicksPerSecond {
    set {
      AssimpPINVOKE.Animation_TicksPerSecond_set(swigCPtr, value);
    } 
    get {
      double ret = AssimpPINVOKE.Animation_TicksPerSecond_get(swigCPtr);
      return ret;
    } 
  }

  public uint NumChannels {
    set {
      AssimpPINVOKE.Animation_NumChannels_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.Animation_NumChannels_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_p_aiNodeAnim Channels {
    set {
      AssimpPINVOKE.Animation_Channels_set(swigCPtr, SWIGTYPE_p_p_aiNodeAnim.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Animation_Channels_get(swigCPtr);
      SWIGTYPE_p_p_aiNodeAnim ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_aiNodeAnim(cPtr, false);
      return ret;
    } 
  }

  public uint NumMeshChannels {
    set {
      AssimpPINVOKE.Animation_NumMeshChannels_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.Animation_NumMeshChannels_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_p_aiMeshAnim MeshChannels {
    set {
      AssimpPINVOKE.Animation_MeshChannels_set(swigCPtr, SWIGTYPE_p_p_aiMeshAnim.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Animation_MeshChannels_get(swigCPtr);
      SWIGTYPE_p_p_aiMeshAnim ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_aiMeshAnim(cPtr, false);
      return ret;
    } 
  }

  public uint NumMorphMeshChannels {
    set {
      AssimpPINVOKE.Animation_NumMorphMeshChannels_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.Animation_NumMorphMeshChannels_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_p_aiMeshMorphAnim MorphMeshChannels {
    set {
      AssimpPINVOKE.Animation_MorphMeshChannels_set(swigCPtr, SWIGTYPE_p_p_aiMeshMorphAnim.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Animation_MorphMeshChannels_get(swigCPtr);
      SWIGTYPE_p_p_aiMeshMorphAnim ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_aiMeshMorphAnim(cPtr, false);
      return ret;
    } 
  }

  public Animation() : this(AssimpPINVOKE.new_Animation(), true) {
  }

}

}
