//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public class Camera : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Camera(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Camera obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Camera obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Camera() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AssimpPINVOKE.delete_Camera(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public String Name {
    set {
      AssimpPINVOKE.Camera_Name_set(swigCPtr, String.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Camera_Name_get(swigCPtr);
      String ret = (cPtr == global::System.IntPtr.Zero) ? null : new String(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_aiVector3tT_float_t Position {
    set {
      AssimpPINVOKE.Camera_Position_set(swigCPtr, SWIGTYPE_p_aiVector3tT_float_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Camera_Position_get(swigCPtr);
      SWIGTYPE_p_aiVector3tT_float_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_aiVector3tT_float_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_aiVector3tT_float_t Up {
    set {
      AssimpPINVOKE.Camera_Up_set(swigCPtr, SWIGTYPE_p_aiVector3tT_float_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Camera_Up_get(swigCPtr);
      SWIGTYPE_p_aiVector3tT_float_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_aiVector3tT_float_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_aiVector3tT_float_t LookAt {
    set {
      AssimpPINVOKE.Camera_LookAt_set(swigCPtr, SWIGTYPE_p_aiVector3tT_float_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Camera_LookAt_get(swigCPtr);
      SWIGTYPE_p_aiVector3tT_float_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_aiVector3tT_float_t(cPtr, false);
      return ret;
    } 
  }

  public float HorizontalFOV {
    set {
      AssimpPINVOKE.Camera_HorizontalFOV_set(swigCPtr, value);
    } 
    get {
      float ret = AssimpPINVOKE.Camera_HorizontalFOV_get(swigCPtr);
      return ret;
    } 
  }

  public float ClipPlaneNear {
    set {
      AssimpPINVOKE.Camera_ClipPlaneNear_set(swigCPtr, value);
    } 
    get {
      float ret = AssimpPINVOKE.Camera_ClipPlaneNear_get(swigCPtr);
      return ret;
    } 
  }

  public float ClipPlaneFar {
    set {
      AssimpPINVOKE.Camera_ClipPlaneFar_set(swigCPtr, value);
    } 
    get {
      float ret = AssimpPINVOKE.Camera_ClipPlaneFar_get(swigCPtr);
      return ret;
    } 
  }

  public float Aspect {
    set {
      AssimpPINVOKE.Camera_Aspect_set(swigCPtr, value);
    } 
    get {
      float ret = AssimpPINVOKE.Camera_Aspect_get(swigCPtr);
      return ret;
    } 
  }

  public float OrthographicWidth {
    set {
      AssimpPINVOKE.Camera_OrthographicWidth_set(swigCPtr, value);
    } 
    get {
      float ret = AssimpPINVOKE.Camera_OrthographicWidth_get(swigCPtr);
      return ret;
    } 
  }

  public Camera() : this(AssimpPINVOKE.new_Camera(), true) {
  }

  public void GetCameraMatrix(SWIGTYPE_p_aiMatrix4x4tT_float_t out_) {
    AssimpPINVOKE.Camera_GetCameraMatrix(swigCPtr, SWIGTYPE_p_aiMatrix4x4tT_float_t.getCPtr(out_));
    if (AssimpPINVOKE.SWIGPendingException.Pending) throw AssimpPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
