//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public class MaterialProperty : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MaterialProperty(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MaterialProperty obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(MaterialProperty obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~MaterialProperty() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AssimpPINVOKE.delete_MaterialProperty(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public String Key {
    set {
      AssimpPINVOKE.MaterialProperty_Key_set(swigCPtr, String.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.MaterialProperty_Key_get(swigCPtr);
      String ret = (cPtr == global::System.IntPtr.Zero) ? null : new String(cPtr, false);
      return ret;
    } 
  }

  public uint Semantic {
    set {
      AssimpPINVOKE.MaterialProperty_Semantic_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.MaterialProperty_Semantic_get(swigCPtr);
      return ret;
    } 
  }

  public uint Index {
    set {
      AssimpPINVOKE.MaterialProperty_Index_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.MaterialProperty_Index_get(swigCPtr);
      return ret;
    } 
  }

  public uint DataLength {
    set {
      AssimpPINVOKE.MaterialProperty_DataLength_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.MaterialProperty_DataLength_get(swigCPtr);
      return ret;
    } 
  }

  public PropertyTypeInfo Type {
    set {
      AssimpPINVOKE.MaterialProperty_Type_set(swigCPtr, (int)value);
    } 
    get {
      PropertyTypeInfo ret = (PropertyTypeInfo)AssimpPINVOKE.MaterialProperty_Type_get(swigCPtr);
      return ret;
    } 
  }

  public string Data {
    set {
      AssimpPINVOKE.MaterialProperty_Data_set(swigCPtr, value);
    } 
    get {
      string ret = AssimpPINVOKE.MaterialProperty_Data_get(swigCPtr);
      return ret;
    } 
  }

  public MaterialProperty() : this(AssimpPINVOKE.new_MaterialProperty(), true) {
  }

}

}
