//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public class Mesh : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Mesh(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Mesh obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Mesh obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Mesh() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AssimpPINVOKE.delete_Mesh(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint PrimitiveTypes {
    set {
      AssimpPINVOKE.Mesh_PrimitiveTypes_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.Mesh_PrimitiveTypes_get(swigCPtr);
      return ret;
    } 
  }

  public uint NumVertices {
    set {
      AssimpPINVOKE.Mesh_NumVertices_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.Mesh_NumVertices_get(swigCPtr);
      return ret;
    } 
  }

  public uint NumFaces {
    set {
      AssimpPINVOKE.Mesh_NumFaces_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.Mesh_NumFaces_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_aiVector3tT_float_t Vertices {
    set {
      AssimpPINVOKE.Mesh_Vertices_set(swigCPtr, SWIGTYPE_p_aiVector3tT_float_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Mesh_Vertices_get(swigCPtr);
      SWIGTYPE_p_aiVector3tT_float_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_aiVector3tT_float_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_aiVector3tT_float_t Normals {
    set {
      AssimpPINVOKE.Mesh_Normals_set(swigCPtr, SWIGTYPE_p_aiVector3tT_float_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Mesh_Normals_get(swigCPtr);
      SWIGTYPE_p_aiVector3tT_float_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_aiVector3tT_float_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_aiVector3tT_float_t Tangents {
    set {
      AssimpPINVOKE.Mesh_Tangents_set(swigCPtr, SWIGTYPE_p_aiVector3tT_float_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Mesh_Tangents_get(swigCPtr);
      SWIGTYPE_p_aiVector3tT_float_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_aiVector3tT_float_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_aiVector3tT_float_t Bitangents {
    set {
      AssimpPINVOKE.Mesh_Bitangents_set(swigCPtr, SWIGTYPE_p_aiVector3tT_float_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Mesh_Bitangents_get(swigCPtr);
      SWIGTYPE_p_aiVector3tT_float_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_aiVector3tT_float_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_p_aiColor4tT_float_t Colors {
    set {
      AssimpPINVOKE.Mesh_Colors_set(swigCPtr, SWIGTYPE_p_p_aiColor4tT_float_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Mesh_Colors_get(swigCPtr);
      SWIGTYPE_p_p_aiColor4tT_float_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_aiColor4tT_float_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_p_aiVector3tT_float_t TextureCoords {
    set {
      AssimpPINVOKE.Mesh_TextureCoords_set(swigCPtr, SWIGTYPE_p_p_aiVector3tT_float_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Mesh_TextureCoords_get(swigCPtr);
      SWIGTYPE_p_p_aiVector3tT_float_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_aiVector3tT_float_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_unsigned_int NumUVComponents {
    set {
      AssimpPINVOKE.Mesh_NumUVComponents_set(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Mesh_NumUVComponents_get(swigCPtr);
      SWIGTYPE_p_unsigned_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
      return ret;
    } 
  }

  public Face Faces {
    set {
      AssimpPINVOKE.Mesh_Faces_set(swigCPtr, Face.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Mesh_Faces_get(swigCPtr);
      Face ret = (cPtr == global::System.IntPtr.Zero) ? null : new Face(cPtr, false);
      return ret;
    } 
  }

  public uint NumBones {
    set {
      AssimpPINVOKE.Mesh_NumBones_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.Mesh_NumBones_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_p_aiBone Bones {
    set {
      AssimpPINVOKE.Mesh_Bones_set(swigCPtr, SWIGTYPE_p_p_aiBone.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Mesh_Bones_get(swigCPtr);
      SWIGTYPE_p_p_aiBone ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_aiBone(cPtr, false);
      return ret;
    } 
  }

  public uint MaterialIndex {
    set {
      AssimpPINVOKE.Mesh_MaterialIndex_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.Mesh_MaterialIndex_get(swigCPtr);
      return ret;
    } 
  }

  public String Name {
    set {
      AssimpPINVOKE.Mesh_Name_set(swigCPtr, String.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Mesh_Name_get(swigCPtr);
      String ret = (cPtr == global::System.IntPtr.Zero) ? null : new String(cPtr, false);
      return ret;
    } 
  }

  public uint NumAnimMeshes {
    set {
      AssimpPINVOKE.Mesh_NumAnimMeshes_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.Mesh_NumAnimMeshes_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_p_aiAnimMesh AnimMeshes {
    set {
      AssimpPINVOKE.Mesh_AnimMeshes_set(swigCPtr, SWIGTYPE_p_p_aiAnimMesh.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Mesh_AnimMeshes_get(swigCPtr);
      SWIGTYPE_p_p_aiAnimMesh ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_aiAnimMesh(cPtr, false);
      return ret;
    } 
  }

  public MorphingMethod Method {
    set {
      AssimpPINVOKE.Mesh_Method_set(swigCPtr, (int)value);
    } 
    get {
      MorphingMethod ret = (MorphingMethod)AssimpPINVOKE.Mesh_Method_get(swigCPtr);
      return ret;
    } 
  }

  public AABB AABB {
    set {
      AssimpPINVOKE.Mesh_AABB_set(swigCPtr, AABB.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Mesh_AABB_get(swigCPtr);
      AABB ret = (cPtr == global::System.IntPtr.Zero) ? null : new AABB(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_p_aiString TextureCoordsNames {
    set {
      AssimpPINVOKE.Mesh_TextureCoordsNames_set(swigCPtr, SWIGTYPE_p_p_aiString.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Mesh_TextureCoordsNames_get(swigCPtr);
      SWIGTYPE_p_p_aiString ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_aiString(cPtr, false);
      return ret;
    } 
  }

  public Mesh() : this(AssimpPINVOKE.new_Mesh(), true) {
  }

  public bool HasPositions() {
    bool ret = AssimpPINVOKE.Mesh_HasPositions(swigCPtr);
    return ret;
  }

  public bool HasFaces() {
    bool ret = AssimpPINVOKE.Mesh_HasFaces(swigCPtr);
    return ret;
  }

  public bool HasNormals() {
    bool ret = AssimpPINVOKE.Mesh_HasNormals(swigCPtr);
    return ret;
  }

  public bool HasTangentsAndBitangents() {
    bool ret = AssimpPINVOKE.Mesh_HasTangentsAndBitangents(swigCPtr);
    return ret;
  }

  public bool HasVertexColors(uint index) {
    bool ret = AssimpPINVOKE.Mesh_HasVertexColors(swigCPtr, index);
    return ret;
  }

  public bool HasTextureCoords(uint index) {
    bool ret = AssimpPINVOKE.Mesh_HasTextureCoords(swigCPtr, index);
    return ret;
  }

  public uint GetNumUVChannels() {
    uint ret = AssimpPINVOKE.Mesh_GetNumUVChannels(swigCPtr);
    return ret;
  }

  public uint GetNumColorChannels() {
    uint ret = AssimpPINVOKE.Mesh_GetNumColorChannels(swigCPtr);
    return ret;
  }

  public bool HasBones() {
    bool ret = AssimpPINVOKE.Mesh_HasBones(swigCPtr);
    return ret;
  }

  public bool HasTextureCoordsName(uint pIndex) {
    bool ret = AssimpPINVOKE.Mesh_HasTextureCoordsName(swigCPtr, pIndex);
    return ret;
  }

  public void SetTextureCoordsName(uint pIndex, String texCoordsName) {
    AssimpPINVOKE.Mesh_SetTextureCoordsName(swigCPtr, pIndex, String.getCPtr(texCoordsName));
    if (AssimpPINVOKE.SWIGPendingException.Pending) throw AssimpPINVOKE.SWIGPendingException.Retrieve();
  }

  public String GetTextureCoordsName(uint index) {
    global::System.IntPtr cPtr = AssimpPINVOKE.Mesh_GetTextureCoordsName(swigCPtr, index);
    String ret = (cPtr == global::System.IntPtr.Zero) ? null : new String(cPtr, false);
    return ret;
  }

}

}
