//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public class Metadata : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Metadata(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Metadata obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Metadata obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Metadata() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AssimpPINVOKE.delete_Metadata(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint NumProperties {
    set {
      AssimpPINVOKE.Metadata_NumProperties_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.Metadata_NumProperties_get(swigCPtr);
      return ret;
    } 
  }

  public String Keys {
    set {
      AssimpPINVOKE.Metadata_Keys_set(swigCPtr, String.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Metadata_Keys_get(swigCPtr);
      String ret = (cPtr == global::System.IntPtr.Zero) ? null : new String(cPtr, false);
      return ret;
    } 
  }

  public MetadataEntry Values {
    set {
      AssimpPINVOKE.Metadata_Values_set(swigCPtr, MetadataEntry.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Metadata_Values_get(swigCPtr);
      MetadataEntry ret = (cPtr == global::System.IntPtr.Zero) ? null : new MetadataEntry(cPtr, false);
      return ret;
    } 
  }

  public Metadata() : this(AssimpPINVOKE.new_Metadata__SWIG_0(), true) {
  }

  public Metadata(Metadata rhs) : this(AssimpPINVOKE.new_Metadata__SWIG_1(Metadata.getCPtr(rhs)), true) {
    if (AssimpPINVOKE.SWIGPendingException.Pending) throw AssimpPINVOKE.SWIGPendingException.Retrieve();
  }

  public static Metadata Alloc(uint numProperties) {
    global::System.IntPtr cPtr = AssimpPINVOKE.Metadata_Alloc(numProperties);
    Metadata ret = (cPtr == global::System.IntPtr.Zero) ? null : new Metadata(cPtr, false);
    return ret;
  }

  public static void Dealloc(Metadata metadata) {
    AssimpPINVOKE.Metadata_Dealloc(Metadata.getCPtr(metadata));
  }

  public bool Get(uint index, SWIGTYPE_p_p_aiString key, SWIGTYPE_p_p_aiMetadataEntry entry) {
    bool ret = AssimpPINVOKE.Metadata_Get(swigCPtr, index, SWIGTYPE_p_p_aiString.getCPtr(key), SWIGTYPE_p_p_aiMetadataEntry.getCPtr(entry));
    if (AssimpPINVOKE.SWIGPendingException.Pending) throw AssimpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool HasKey(string key) {
    bool ret = AssimpPINVOKE.Metadata_HasKey(swigCPtr, key);
    return ret;
  }

}

}
