//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public enum MetadataType {
  AI_BOOL = 0,
  AI_INT32 = 1,
  AI_UINT64 = 2,
  AI_FLOAT = 3,
  AI_DOUBLE = 4,
  AI_AISTRING = 5,
  AI_AIVECTOR3D = 6,
  AI_AIMETADATA = 7,
  AI_INT64 = 8,
  AI_UINT32 = 9,
  AI_META_MAX = 10
}

}
