//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public class Plane : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Plane(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Plane obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Plane obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Plane() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AssimpPINVOKE.delete_Plane(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Plane() : this(AssimpPINVOKE.new_Plane__SWIG_0(), true) {
  }

  public Plane(float _a, float _b, float _c, float _d) : this(AssimpPINVOKE.new_Plane__SWIG_1(_a, _b, _c, _d), true) {
  }

  public Plane(Plane o) : this(AssimpPINVOKE.new_Plane__SWIG_2(Plane.getCPtr(o)), true) {
    if (AssimpPINVOKE.SWIGPendingException.Pending) throw AssimpPINVOKE.SWIGPendingException.Retrieve();
  }

  public float a {
    set {
      AssimpPINVOKE.Plane_a_set(swigCPtr, value);
    } 
    get {
      float ret = AssimpPINVOKE.Plane_a_get(swigCPtr);
      return ret;
    } 
  }

  public float b {
    set {
      AssimpPINVOKE.Plane_b_set(swigCPtr, value);
    } 
    get {
      float ret = AssimpPINVOKE.Plane_b_get(swigCPtr);
      return ret;
    } 
  }

  public float c {
    set {
      AssimpPINVOKE.Plane_c_set(swigCPtr, value);
    } 
    get {
      float ret = AssimpPINVOKE.Plane_c_get(swigCPtr);
      return ret;
    } 
  }

  public float d {
    set {
      AssimpPINVOKE.Plane_d_set(swigCPtr, value);
    } 
    get {
      float ret = AssimpPINVOKE.Plane_d_get(swigCPtr);
      return ret;
    } 
  }

}

}
