//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public class SkeletonBone : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SkeletonBone(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SkeletonBone obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(SkeletonBone obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~SkeletonBone() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AssimpPINVOKE.delete_SkeletonBone(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int Parent {
    set {
      AssimpPINVOKE.SkeletonBone_Parent_set(swigCPtr, value);
    } 
    get {
      int ret = AssimpPINVOKE.SkeletonBone_Parent_get(swigCPtr);
      return ret;
    } 
  }

  public Node Armature {
    set {
      AssimpPINVOKE.SkeletonBone_Armature_set(swigCPtr, Node.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.SkeletonBone_Armature_get(swigCPtr);
      Node ret = (cPtr == global::System.IntPtr.Zero) ? null : new Node(cPtr, false);
      return ret;
    } 
  }

  public Node Node {
    set {
      AssimpPINVOKE.SkeletonBone_Node_set(swigCPtr, Node.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.SkeletonBone_Node_get(swigCPtr);
      Node ret = (cPtr == global::System.IntPtr.Zero) ? null : new Node(cPtr, false);
      return ret;
    } 
  }

  public uint NumnWeights {
    set {
      AssimpPINVOKE.SkeletonBone_NumnWeights_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.SkeletonBone_NumnWeights_get(swigCPtr);
      return ret;
    } 
  }

  public Mesh MeshId {
    set {
      AssimpPINVOKE.SkeletonBone_MeshId_set(swigCPtr, Mesh.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.SkeletonBone_MeshId_get(swigCPtr);
      Mesh ret = (cPtr == global::System.IntPtr.Zero) ? null : new Mesh(cPtr, false);
      return ret;
    } 
  }

  public VertexWeight Weights {
    set {
      AssimpPINVOKE.SkeletonBone_Weights_set(swigCPtr, VertexWeight.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.SkeletonBone_Weights_get(swigCPtr);
      VertexWeight ret = (cPtr == global::System.IntPtr.Zero) ? null : new VertexWeight(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_aiMatrix4x4tT_float_t OffsetMatrix {
    set {
      AssimpPINVOKE.SkeletonBone_OffsetMatrix_set(swigCPtr, SWIGTYPE_p_aiMatrix4x4tT_float_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.SkeletonBone_OffsetMatrix_get(swigCPtr);
      SWIGTYPE_p_aiMatrix4x4tT_float_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_aiMatrix4x4tT_float_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_aiMatrix4x4tT_float_t LocalMatrix {
    set {
      AssimpPINVOKE.SkeletonBone_LocalMatrix_set(swigCPtr, SWIGTYPE_p_aiMatrix4x4tT_float_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.SkeletonBone_LocalMatrix_get(swigCPtr);
      SWIGTYPE_p_aiMatrix4x4tT_float_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_aiMatrix4x4tT_float_t(cPtr, false);
      return ret;
    } 
  }

  public SkeletonBone() : this(AssimpPINVOKE.new_SkeletonBone__SWIG_0(), true) {
  }

  public SkeletonBone(uint parent) : this(AssimpPINVOKE.new_SkeletonBone__SWIG_1(parent), true) {
  }

}

}
