//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public enum TextureFlags {
  TextureFlags_Invert = 1,
  TextureFlags_UseAlpha = 2,
  TextureFlags_IgnoreAlpha = 4
}

}
