//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public enum AnimBehaviour {
  AnimBehaviour_DEFAULT = 0,
  AnimBehaviour_CONSTANT = 1,
  AnimBehaviour_LINEAR = 2,
  AnimBehaviour_REPEAT = 3
}

}
