//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public class Color3D : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Color3D(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Color3D obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Color3D obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Color3D() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AssimpPINVOKE.delete_Color3D(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Color3D() : this(AssimpPINVOKE.new_Color3D__SWIG_0(), true) {
  }

  public Color3D(float _r, float _g, float _b) : this(AssimpPINVOKE.new_Color3D__SWIG_1(_r, _g, _b), true) {
  }

  public Color3D(float _r) : this(AssimpPINVOKE.new_Color3D__SWIG_2(_r), true) {
  }

  public Color3D(Color3D o) : this(AssimpPINVOKE.new_Color3D__SWIG_3(Color3D.getCPtr(o)), true) {
    if (AssimpPINVOKE.SWIGPendingException.Pending) throw AssimpPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool IsBlack() {
    bool ret = AssimpPINVOKE.Color3D_IsBlack(swigCPtr);
    return ret;
  }

  public float r {
    set {
      AssimpPINVOKE.Color3D_r_set(swigCPtr, value);
    } 
    get {
      float ret = AssimpPINVOKE.Color3D_r_get(swigCPtr);
      return ret;
    } 
  }

  public float g {
    set {
      AssimpPINVOKE.Color3D_g_set(swigCPtr, value);
    } 
    get {
      float ret = AssimpPINVOKE.Color3D_g_get(swigCPtr);
      return ret;
    } 
  }

  public float b {
    set {
      AssimpPINVOKE.Color3D_b_set(swigCPtr, value);
    } 
    get {
      float ret = AssimpPINVOKE.Color3D_b_get(swigCPtr);
      return ret;
    } 
  }

}

}
