//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public enum LightSourceType {
  LightSource_UNDEFINED = 0,
  LightSource_DIRECTIONAL = 1,
  LightSource_POINT = 2,
  LightSource_SPOT = 3,
  LightSource_AMBIENT = 4,
  LightSource_AREA = 5
}

}
