//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public class MeshAnim : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MeshAnim(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MeshAnim obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(MeshAnim obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~MeshAnim() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AssimpPINVOKE.delete_MeshAnim(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public String Name {
    set {
      AssimpPINVOKE.MeshAnim_Name_set(swigCPtr, String.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.MeshAnim_Name_get(swigCPtr);
      String ret = (cPtr == global::System.IntPtr.Zero) ? null : new String(cPtr, false);
      return ret;
    } 
  }

  public uint NumKeys {
    set {
      AssimpPINVOKE.MeshAnim_NumKeys_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.MeshAnim_NumKeys_get(swigCPtr);
      return ret;
    } 
  }

  public MeshKey Keys {
    set {
      AssimpPINVOKE.MeshAnim_Keys_set(swigCPtr, MeshKey.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.MeshAnim_Keys_get(swigCPtr);
      MeshKey ret = (cPtr == global::System.IntPtr.Zero) ? null : new MeshKey(cPtr, false);
      return ret;
    } 
  }

  public MeshAnim() : this(AssimpPINVOKE.new_MeshAnim(), true) {
  }

}

}
