//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public enum PropertyTypeInfo {
  PTI_Float = 1,
  PTI_Double = 2,
  PTI_String = 3,
  PTI_Integer = 4,
  PTI_Buffer = 5
}

}
