//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public class String : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal String(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(String obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(String obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~String() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AssimpPINVOKE.delete_String(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public String() : this(AssimpPINVOKE.new_String__SWIG_0(), true) {
  }

  public String(String rOther) : this(AssimpPINVOKE.new_String__SWIG_1(String.getCPtr(rOther)), true) {
    if (AssimpPINVOKE.SWIGPendingException.Pending) throw AssimpPINVOKE.SWIGPendingException.Retrieve();
  }

  public String(SWIGTYPE_p_std__string pString) : this(AssimpPINVOKE.new_String__SWIG_2(SWIGTYPE_p_std__string.getCPtr(pString)), true) {
    if (AssimpPINVOKE.SWIGPendingException.Pending) throw AssimpPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Set(SWIGTYPE_p_std__string pString) {
    AssimpPINVOKE.String_Set__SWIG_0(swigCPtr, SWIGTYPE_p_std__string.getCPtr(pString));
    if (AssimpPINVOKE.SWIGPendingException.Pending) throw AssimpPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Set(string sz, uint maxlen) {
    AssimpPINVOKE.String_Set__SWIG_1(swigCPtr, sz, maxlen);
  }

  public string C_Str() {
    string ret = AssimpPINVOKE.String_C_Str(swigCPtr);
    return ret;
  }

  public bool Empty() {
    bool ret = AssimpPINVOKE.String_Empty(swigCPtr);
    return ret;
  }

  public uint length {
    set {
      AssimpPINVOKE.String_length_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.String_length_get(swigCPtr);
      return ret;
    } 
  }

  public string data {
    set {
      AssimpPINVOKE.String_data_set(swigCPtr, value);
    } 
    get {
      string ret = AssimpPINVOKE.String_data_get(swigCPtr);
      return ret;
    } 
  }

}

}
