//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public class Texture : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Texture(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Texture obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Texture obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Texture() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AssimpPINVOKE.delete_Texture(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint Width {
    set {
      AssimpPINVOKE.Texture_Width_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.Texture_Width_get(swigCPtr);
      return ret;
    } 
  }

  public uint Height {
    set {
      AssimpPINVOKE.Texture_Height_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.Texture_Height_get(swigCPtr);
      return ret;
    } 
  }

  public string achFormatHint {
    set {
      AssimpPINVOKE.Texture_achFormatHint_set(swigCPtr, value);
    } 
    get {
      string ret = AssimpPINVOKE.Texture_achFormatHint_get(swigCPtr);
      return ret;
    } 
  }

  public Texel pcData {
    set {
      AssimpPINVOKE.Texture_pcData_set(swigCPtr, Texel.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Texture_pcData_get(swigCPtr);
      Texel ret = (cPtr == global::System.IntPtr.Zero) ? null : new Texel(cPtr, false);
      return ret;
    } 
  }

  public String Filename {
    set {
      AssimpPINVOKE.Texture_Filename_set(swigCPtr, String.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Texture_Filename_get(swigCPtr);
      String ret = (cPtr == global::System.IntPtr.Zero) ? null : new String(cPtr, false);
      return ret;
    } 
  }

  public bool CheckFormat(string s) {
    bool ret = AssimpPINVOKE.Texture_CheckFormat(swigCPtr, s);
    return ret;
  }

  public Texture() : this(AssimpPINVOKE.new_Texture(), true) {
  }

}

}
