<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-android</TargetFramework>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>Assimp</RootNamespace>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">24.0</SupportedOSPlatformVersion>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
	</PropertyGroup>
	
	<PropertyGroup Condition="'$(IsOfficialBuild)' == 'true'">
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    </PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<DebugSymbols>true</DebugSymbols>
		<DebugType>portable</DebugType>
	</PropertyGroup>

	<PropertyGroup>
        <PackageId>Assimp.Maui.Android</PackageId>
        <Version>6.0.5.0-rc1</Version>
        <AssemblyVersion>6.0.5.0</AssemblyVersion>
        <FileVersion>6.0.5.0</FileVersion>
        <Title>Assimp.Maui</Title>
        <Authors>Weslley Murdock</Authors>
        <Company>Remote Code Hub</Company>
        <Copyright>Copyright ©2026 Remote Code Hub</Copyright>
        <PackageTags>assimp;net;maui;native;assimp-net;android;ios;windows;maccatalyst;scene;game;game-dev;engine;assets;asset;3d</PackageTags>
		<Description>**Assimp.MAUI** is a .NET MAUI wrapper and cross-platform binary distribution for the [Open Asset Import Library (Assimp)](https://github.com/assimp/assimp). This package bundles pre-compiled native Assimp binaries targeting all .NET MAUI supported platforms and Runtime Identifiers (RIDs), enabling seamless loading and processing of over 40 3D model formats (such as OBJ, FBX, GLTF, COLLADA, and STL) in cross-platform applications.</Description>
        <PackageProjectUrl>https://github.com/weslleymurdock/Assimp.MAUI</PackageProjectUrl>
        <RepositoryUrl>https://github.com/weslleymurdock/Assimp.MAUI.git</RepositoryUrl>
    </PropertyGroup>

	<ItemGroup>
	    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
	</ItemGroup>

</Project>
