//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public class AnimMesh : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal AnimMesh(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(AnimMesh obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(AnimMesh obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~AnimMesh() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AssimpPINVOKE.delete_AnimMesh(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public String Name {
    set {
      AssimpPINVOKE.AnimMesh_Name_set(swigCPtr, String.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.AnimMesh_Name_get(swigCPtr);
      String ret = (cPtr == global::System.IntPtr.Zero) ? null : new String(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_aiVector3tT_float_t Vertices {
    set {
      AssimpPINVOKE.AnimMesh_Vertices_set(swigCPtr, SWIGTYPE_p_aiVector3tT_float_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.AnimMesh_Vertices_get(swigCPtr);
      SWIGTYPE_p_aiVector3tT_float_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_aiVector3tT_float_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_aiVector3tT_float_t Normals {
    set {
      AssimpPINVOKE.AnimMesh_Normals_set(swigCPtr, SWIGTYPE_p_aiVector3tT_float_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.AnimMesh_Normals_get(swigCPtr);
      SWIGTYPE_p_aiVector3tT_float_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_aiVector3tT_float_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_aiVector3tT_float_t Tangents {
    set {
      AssimpPINVOKE.AnimMesh_Tangents_set(swigCPtr, SWIGTYPE_p_aiVector3tT_float_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.AnimMesh_Tangents_get(swigCPtr);
      SWIGTYPE_p_aiVector3tT_float_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_aiVector3tT_float_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_aiVector3tT_float_t Bitangents {
    set {
      AssimpPINVOKE.AnimMesh_Bitangents_set(swigCPtr, SWIGTYPE_p_aiVector3tT_float_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.AnimMesh_Bitangents_get(swigCPtr);
      SWIGTYPE_p_aiVector3tT_float_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_aiVector3tT_float_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_p_aiColor4tT_float_t Colors {
    set {
      AssimpPINVOKE.AnimMesh_Colors_set(swigCPtr, SWIGTYPE_p_p_aiColor4tT_float_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.AnimMesh_Colors_get(swigCPtr);
      SWIGTYPE_p_p_aiColor4tT_float_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_aiColor4tT_float_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_p_aiVector3tT_float_t TextureCoords {
    set {
      AssimpPINVOKE.AnimMesh_TextureCoords_set(swigCPtr, SWIGTYPE_p_p_aiVector3tT_float_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.AnimMesh_TextureCoords_get(swigCPtr);
      SWIGTYPE_p_p_aiVector3tT_float_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_aiVector3tT_float_t(cPtr, false);
      return ret;
    } 
  }

  public uint NumVertices {
    set {
      AssimpPINVOKE.AnimMesh_NumVertices_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.AnimMesh_NumVertices_get(swigCPtr);
      return ret;
    } 
  }

  public float Weight {
    set {
      AssimpPINVOKE.AnimMesh_Weight_set(swigCPtr, value);
    } 
    get {
      float ret = AssimpPINVOKE.AnimMesh_Weight_get(swigCPtr);
      return ret;
    } 
  }

  public AnimMesh() : this(AssimpPINVOKE.new_AnimMesh(), true) {
  }

  public bool HasPositions() {
    bool ret = AssimpPINVOKE.AnimMesh_HasPositions(swigCPtr);
    return ret;
  }

  public bool HasNormals() {
    bool ret = AssimpPINVOKE.AnimMesh_HasNormals(swigCPtr);
    return ret;
  }

  public bool HasTangentsAndBitangents() {
    bool ret = AssimpPINVOKE.AnimMesh_HasTangentsAndBitangents(swigCPtr);
    return ret;
  }

  public bool HasVertexColors(uint pIndex) {
    bool ret = AssimpPINVOKE.AnimMesh_HasVertexColors(swigCPtr, pIndex);
    return ret;
  }

  public bool HasTextureCoords(uint pIndex) {
    bool ret = AssimpPINVOKE.AnimMesh_HasTextureCoords(swigCPtr, pIndex);
    return ret;
  }

}

}
