//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public enum DefaultLogStream {
  DefaultLogStream_FILE = 1,
  DefaultLogStream_STDOUT = 2,
  DefaultLogStream_STDERR = 4,
  DefaultLogStream_DEBUGGER = 8,
  _AI_DLS_ENFORCE_ENUM_SIZE = 2147483647
}

}
