//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public class File : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal File(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(File obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(File obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~File() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AssimpPINVOKE.delete_File(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public virtual uint Read(string buffer, uint size, uint count) {
    uint ret = AssimpPINVOKE.File_Read(swigCPtr, buffer, size, count);
    return ret;
  }

  public virtual uint Write(string buffer, uint size, uint count) {
    uint ret = AssimpPINVOKE.File_Write(swigCPtr, buffer, size, count);
    return ret;
  }

  public virtual uint Tell() {
    uint ret = AssimpPINVOKE.File_Tell(swigCPtr);
    return ret;
  }

  public virtual Return Seek(uint offset, Origin origin) {
    Return ret = (Return)AssimpPINVOKE.File_Seek(swigCPtr, offset, (int)origin);
    return ret;
  }

  public virtual void Flush() {
    AssimpPINVOKE.File_Flush(swigCPtr);
  }

  public File() : this(AssimpPINVOKE.new_File(), true) {
    SwigDirectorConnect();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("Read", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateFile_0(SwigDirectorMethodRead);
    if (SwigDerivedClassHasMethod("Write", swigMethodTypes1))
      swigDelegate1 = new SwigDelegateFile_1(SwigDirectorMethodWrite);
    if (SwigDerivedClassHasMethod("Tell", swigMethodTypes2))
      swigDelegate2 = new SwigDelegateFile_2(SwigDirectorMethodTell);
    if (SwigDerivedClassHasMethod("Seek", swigMethodTypes3))
      swigDelegate3 = new SwigDelegateFile_3(SwigDirectorMethodSeek);
    if (SwigDerivedClassHasMethod("Flush", swigMethodTypes4))
      swigDelegate4 = new SwigDelegateFile_4(SwigDirectorMethodFlush);
    AssimpPINVOKE.File_director_connect(swigCPtr, swigDelegate0, swigDelegate1, swigDelegate2, swigDelegate3, swigDelegate4);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo[] methodInfos = this.GetType().GetMethods(
        global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance);
    foreach (global::System.Reflection.MethodInfo methodInfo in methodInfos) {
      if (methodInfo.DeclaringType == null)
        continue;

      if (methodInfo.Name != methodName)
        continue;

      var parameters = methodInfo.GetParameters();
      if (parameters.Length != methodTypes.Length)
        continue;

      bool parametersMatch = true;
      for (var i = 0; i < parameters.Length; i++) {
        if (parameters[i].ParameterType != methodTypes[i]) {
          parametersMatch = false;
          break;
        }
      }

      if (!parametersMatch)
        continue;

      if (methodInfo.IsVirtual && (methodInfo.DeclaringType.IsSubclassOf(typeof(File))) &&
        methodInfo.DeclaringType != methodInfo.GetBaseDefinition().DeclaringType) {
        return true;
      }
    }

    return false;
  }

  private uint SwigDirectorMethodRead(string buffer, uint size, uint count) {
    return Read(buffer, size, count);
  }

  private uint SwigDirectorMethodWrite(string buffer, uint size, uint count) {
    return Write(buffer, size, count);
  }

  private uint SwigDirectorMethodTell() {
    return Tell();
  }

  private int SwigDirectorMethodSeek(uint offset, int origin) {
    return (int)Seek(offset, (Origin)origin);
  }

  private void SwigDirectorMethodFlush() {
    Flush();
  }

  public delegate uint SwigDelegateFile_0(string buffer, uint size, uint count);
  public delegate uint SwigDelegateFile_1(string buffer, uint size, uint count);
  public delegate uint SwigDelegateFile_2();
  public delegate int SwigDelegateFile_3(uint offset, int origin);
  public delegate void SwigDelegateFile_4();

  private SwigDelegateFile_0 swigDelegate0;
  private SwigDelegateFile_1 swigDelegate1;
  private SwigDelegateFile_2 swigDelegate2;
  private SwigDelegateFile_3 swigDelegate3;
  private SwigDelegateFile_4 swigDelegate4;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] { typeof(string), typeof(uint), typeof(uint) };
  private static global::System.Type[] swigMethodTypes1 = new global::System.Type[] { typeof(string), typeof(uint), typeof(uint) };
  private static global::System.Type[] swigMethodTypes2 = new global::System.Type[] {  };
  private static global::System.Type[] swigMethodTypes3 = new global::System.Type[] { typeof(uint), typeof(Origin) };
  private static global::System.Type[] swigMethodTypes4 = new global::System.Type[] {  };
}

}
