//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public class FileSystem : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal FileSystem(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FileSystem obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(FileSystem obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~FileSystem() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AssimpPINVOKE.delete_FileSystem(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public virtual File Open(string fileName, string openMode) {
    global::System.IntPtr cPtr = AssimpPINVOKE.FileSystem_Open(swigCPtr, fileName, openMode);
    File ret = (cPtr == global::System.IntPtr.Zero) ? null : new File(cPtr, false);
    return ret;
  }

  public virtual void Close(File pFile) {
    AssimpPINVOKE.FileSystem_Close(swigCPtr, File.getCPtr(pFile));
  }

  public FileIO GetNative() {
    FileIO ret = new FileIO(AssimpPINVOKE.FileSystem_GetNative(swigCPtr), true);
    return ret;
  }

  public FileSystem() : this(AssimpPINVOKE.new_FileSystem(), true) {
    SwigDirectorConnect();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("Open", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateFileSystem_0(SwigDirectorMethodOpen);
    if (SwigDerivedClassHasMethod("Close", swigMethodTypes1))
      swigDelegate1 = new SwigDelegateFileSystem_1(SwigDirectorMethodClose);
    AssimpPINVOKE.FileSystem_director_connect(swigCPtr, swigDelegate0, swigDelegate1);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo[] methodInfos = this.GetType().GetMethods(
        global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance);
    foreach (global::System.Reflection.MethodInfo methodInfo in methodInfos) {
      if (methodInfo.DeclaringType == null)
        continue;

      if (methodInfo.Name != methodName)
        continue;

      var parameters = methodInfo.GetParameters();
      if (parameters.Length != methodTypes.Length)
        continue;

      bool parametersMatch = true;
      for (var i = 0; i < parameters.Length; i++) {
        if (parameters[i].ParameterType != methodTypes[i]) {
          parametersMatch = false;
          break;
        }
      }

      if (!parametersMatch)
        continue;

      if (methodInfo.IsVirtual && (methodInfo.DeclaringType.IsSubclassOf(typeof(FileSystem))) &&
        methodInfo.DeclaringType != methodInfo.GetBaseDefinition().DeclaringType) {
        return true;
      }
    }

    return false;
  }

  private global::System.IntPtr SwigDirectorMethodOpen(string fileName, string openMode) {
    return File.getCPtr(Open(fileName, openMode)).Handle;
  }

  private void SwigDirectorMethodClose(global::System.IntPtr pFile) {
    Close((pFile == global::System.IntPtr.Zero) ? null : new File(pFile, false));
  }

  public delegate global::System.IntPtr SwigDelegateFileSystem_0(string fileName, string openMode);
  public delegate void SwigDelegateFileSystem_1(global::System.IntPtr pFile);

  private SwigDelegateFileSystem_0 swigDelegate0;
  private SwigDelegateFileSystem_1 swigDelegate1;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] { typeof(string), typeof(string) };
  private static global::System.Type[] swigMethodTypes1 = new global::System.Type[] { typeof(File) };
}

}
