//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public enum PrimitiveType {
  PrimitiveType_POINT = 1,
  PrimitiveType_LINE = 2,
  PrimitiveType_TRIANGLE = 4,
  PrimitiveType_POLYGON = 8,
  PrimitiveType_NGONEncodingFlag = 16
}

}
