//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public enum TextureMapMode {
  TextureMapMode_Wrap = 0,
  TextureMapMode_Clamp = 1,
  TextureMapMode_Decal = 3,
  TextureMapMode_Mirror = 2
}

}
