//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public enum TextureMapping {
  TextureMapping_UV = 0,
  TextureMapping_SPHERE = 1,
  TextureMapping_CYLINDER = 2,
  TextureMapping_BOX = 3,
  TextureMapping_PLANE = 4,
  TextureMapping_OTHER = 5
}

}
