//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public enum Return {
  Return_SUCCESS = 0,
  Return_FAILURE = -1,
  Return_OUTOFMEMORY = -3,
  _AI_ENFORCE_ENUM_SIZE = 2147483647
}

}
