//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public class Scene : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Scene(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Scene obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Scene obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Scene() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AssimpPINVOKE.delete_Scene(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint Flags {
    set {
      AssimpPINVOKE.Scene_Flags_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.Scene_Flags_get(swigCPtr);
      return ret;
    } 
  }

  public Node RootNode {
    set {
      AssimpPINVOKE.Scene_RootNode_set(swigCPtr, Node.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Scene_RootNode_get(swigCPtr);
      Node ret = (cPtr == global::System.IntPtr.Zero) ? null : new Node(cPtr, false);
      return ret;
    } 
  }

  public uint NumMeshes {
    set {
      AssimpPINVOKE.Scene_NumMeshes_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.Scene_NumMeshes_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_p_aiMesh Meshes {
    set {
      AssimpPINVOKE.Scene_Meshes_set(swigCPtr, SWIGTYPE_p_p_aiMesh.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Scene_Meshes_get(swigCPtr);
      SWIGTYPE_p_p_aiMesh ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_aiMesh(cPtr, false);
      return ret;
    } 
  }

  public uint NumMaterials {
    set {
      AssimpPINVOKE.Scene_NumMaterials_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.Scene_NumMaterials_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_p_aiMaterial Materials {
    set {
      AssimpPINVOKE.Scene_Materials_set(swigCPtr, SWIGTYPE_p_p_aiMaterial.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Scene_Materials_get(swigCPtr);
      SWIGTYPE_p_p_aiMaterial ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_aiMaterial(cPtr, false);
      return ret;
    } 
  }

  public uint NumAnimations {
    set {
      AssimpPINVOKE.Scene_NumAnimations_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.Scene_NumAnimations_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_p_aiAnimation Animations {
    set {
      AssimpPINVOKE.Scene_Animations_set(swigCPtr, SWIGTYPE_p_p_aiAnimation.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Scene_Animations_get(swigCPtr);
      SWIGTYPE_p_p_aiAnimation ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_aiAnimation(cPtr, false);
      return ret;
    } 
  }

  public uint NumTextures {
    set {
      AssimpPINVOKE.Scene_NumTextures_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.Scene_NumTextures_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_p_aiTexture Textures {
    set {
      AssimpPINVOKE.Scene_Textures_set(swigCPtr, SWIGTYPE_p_p_aiTexture.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Scene_Textures_get(swigCPtr);
      SWIGTYPE_p_p_aiTexture ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_aiTexture(cPtr, false);
      return ret;
    } 
  }

  public uint NumLights {
    set {
      AssimpPINVOKE.Scene_NumLights_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.Scene_NumLights_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_p_aiLight Lights {
    set {
      AssimpPINVOKE.Scene_Lights_set(swigCPtr, SWIGTYPE_p_p_aiLight.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Scene_Lights_get(swigCPtr);
      SWIGTYPE_p_p_aiLight ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_aiLight(cPtr, false);
      return ret;
    } 
  }

  public uint NumCameras {
    set {
      AssimpPINVOKE.Scene_NumCameras_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.Scene_NumCameras_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_p_aiCamera Cameras {
    set {
      AssimpPINVOKE.Scene_Cameras_set(swigCPtr, SWIGTYPE_p_p_aiCamera.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Scene_Cameras_get(swigCPtr);
      SWIGTYPE_p_p_aiCamera ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_aiCamera(cPtr, false);
      return ret;
    } 
  }

  public Metadata MetaData {
    set {
      AssimpPINVOKE.Scene_MetaData_set(swigCPtr, Metadata.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Scene_MetaData_get(swigCPtr);
      Metadata ret = (cPtr == global::System.IntPtr.Zero) ? null : new Metadata(cPtr, false);
      return ret;
    } 
  }

  public String Name {
    set {
      AssimpPINVOKE.Scene_Name_set(swigCPtr, String.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Scene_Name_get(swigCPtr);
      String ret = (cPtr == global::System.IntPtr.Zero) ? null : new String(cPtr, false);
      return ret;
    } 
  }

  public uint NumSkeletons {
    set {
      AssimpPINVOKE.Scene_NumSkeletons_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.Scene_NumSkeletons_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_p_aiSkeleton Skeletons {
    set {
      AssimpPINVOKE.Scene_Skeletons_set(swigCPtr, SWIGTYPE_p_p_aiSkeleton.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Scene_Skeletons_get(swigCPtr);
      SWIGTYPE_p_p_aiSkeleton ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_aiSkeleton(cPtr, false);
      return ret;
    } 
  }

  public Scene() : this(AssimpPINVOKE.new_Scene(), true) {
  }

  public bool HasMeshes() {
    bool ret = AssimpPINVOKE.Scene_HasMeshes(swigCPtr);
    return ret;
  }

  public bool HasMaterials() {
    bool ret = AssimpPINVOKE.Scene_HasMaterials(swigCPtr);
    return ret;
  }

  public bool HasLights() {
    bool ret = AssimpPINVOKE.Scene_HasLights(swigCPtr);
    return ret;
  }

  public bool HasTextures() {
    bool ret = AssimpPINVOKE.Scene_HasTextures(swigCPtr);
    return ret;
  }

  public bool HasCameras() {
    bool ret = AssimpPINVOKE.Scene_HasCameras(swigCPtr);
    return ret;
  }

  public bool HasAnimations() {
    bool ret = AssimpPINVOKE.Scene_HasAnimations(swigCPtr);
    return ret;
  }

  public bool HasSkeletons() {
    bool ret = AssimpPINVOKE.Scene_HasSkeletons(swigCPtr);
    return ret;
  }

  public static string GetShortFilename(string filename) {
    string ret = AssimpPINVOKE.Scene_GetShortFilename(filename);
    return ret;
  }

  public Texture GetEmbeddedTexture(string filename) {
    global::System.IntPtr cPtr = AssimpPINVOKE.Scene_GetEmbeddedTexture(swigCPtr, filename);
    Texture ret = (cPtr == global::System.IntPtr.Zero) ? null : new Texture(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_std__pairT_aiTexture_const_p_int_t GetEmbeddedTextureAndIndex(string filename) {
    SWIGTYPE_p_std__pairT_aiTexture_const_p_int_t ret = new SWIGTYPE_p_std__pairT_aiTexture_const_p_int_t(AssimpPINVOKE.Scene_GetEmbeddedTextureAndIndex(swigCPtr, filename), true);
    return ret;
  }

  public Bone findBone(String name) {
    global::System.IntPtr cPtr = AssimpPINVOKE.Scene_findBone(swigCPtr, String.getCPtr(name));
    Bone ret = (cPtr == global::System.IntPtr.Zero) ? null : new Bone(cPtr, false);
    if (AssimpPINVOKE.SWIGPendingException.Pending) throw AssimpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_void Private {
    set {
      AssimpPINVOKE.Scene_Private_set(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Scene_Private_get(swigCPtr);
      SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
      return ret;
    } 
  }

}

}
