//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public enum AnimBehaviour {
  AnimBehaviour_DEFAULT = 0x0,
  AnimBehaviour_CONSTANT = 0x1,
  AnimBehaviour_LINEAR = 0x2,
  AnimBehaviour_REPEAT = 0x3
}

}
