//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public enum AnimInterpolation {
  AnimInterpolation_Step,
  AnimInterpolation_Linear,
  AnimInterpolation_Spherical_Linear,
  AnimInterpolation_Cubic_Spline
}

}
