//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public enum DefaultLogStream {
  DefaultLogStream_FILE = 0x1,
  DefaultLogStream_STDOUT = 0x2,
  DefaultLogStream_STDERR = 0x4,
  DefaultLogStream_DEBUGGER = 0x8,
  _AI_DLS_ENFORCE_ENUM_SIZE = 0x7fffffff
}

}
