//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public class Light : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Light(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Light obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Light obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Light() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AssimpPINVOKE.delete_Light(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public String Name {
    set {
      AssimpPINVOKE.Light_Name_set(swigCPtr, String.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Light_Name_get(swigCPtr);
      String ret = (cPtr == global::System.IntPtr.Zero) ? null : new String(cPtr, false);
      return ret;
    } 
  }

  public LightSourceType Type {
    set {
      AssimpPINVOKE.Light_Type_set(swigCPtr, (int)value);
    } 
    get {
      LightSourceType ret = (LightSourceType)AssimpPINVOKE.Light_Type_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_aiVector3tT_float_t Position {
    set {
      AssimpPINVOKE.Light_Position_set(swigCPtr, SWIGTYPE_p_aiVector3tT_float_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Light_Position_get(swigCPtr);
      SWIGTYPE_p_aiVector3tT_float_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_aiVector3tT_float_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_aiVector3tT_float_t Direction {
    set {
      AssimpPINVOKE.Light_Direction_set(swigCPtr, SWIGTYPE_p_aiVector3tT_float_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Light_Direction_get(swigCPtr);
      SWIGTYPE_p_aiVector3tT_float_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_aiVector3tT_float_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_aiVector3tT_float_t Up {
    set {
      AssimpPINVOKE.Light_Up_set(swigCPtr, SWIGTYPE_p_aiVector3tT_float_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Light_Up_get(swigCPtr);
      SWIGTYPE_p_aiVector3tT_float_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_aiVector3tT_float_t(cPtr, false);
      return ret;
    } 
  }

  public float AttenuationConstant {
    set {
      AssimpPINVOKE.Light_AttenuationConstant_set(swigCPtr, value);
    } 
    get {
      float ret = AssimpPINVOKE.Light_AttenuationConstant_get(swigCPtr);
      return ret;
    } 
  }

  public float AttenuationLinear {
    set {
      AssimpPINVOKE.Light_AttenuationLinear_set(swigCPtr, value);
    } 
    get {
      float ret = AssimpPINVOKE.Light_AttenuationLinear_get(swigCPtr);
      return ret;
    } 
  }

  public float AttenuationQuadratic {
    set {
      AssimpPINVOKE.Light_AttenuationQuadratic_set(swigCPtr, value);
    } 
    get {
      float ret = AssimpPINVOKE.Light_AttenuationQuadratic_get(swigCPtr);
      return ret;
    } 
  }

  public Color3D ColorDiffuse {
    set {
      AssimpPINVOKE.Light_ColorDiffuse_set(swigCPtr, Color3D.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Light_ColorDiffuse_get(swigCPtr);
      Color3D ret = (cPtr == global::System.IntPtr.Zero) ? null : new Color3D(cPtr, false);
      return ret;
    } 
  }

  public Color3D ColorSpecular {
    set {
      AssimpPINVOKE.Light_ColorSpecular_set(swigCPtr, Color3D.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Light_ColorSpecular_get(swigCPtr);
      Color3D ret = (cPtr == global::System.IntPtr.Zero) ? null : new Color3D(cPtr, false);
      return ret;
    } 
  }

  public Color3D ColorAmbient {
    set {
      AssimpPINVOKE.Light_ColorAmbient_set(swigCPtr, Color3D.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Light_ColorAmbient_get(swigCPtr);
      Color3D ret = (cPtr == global::System.IntPtr.Zero) ? null : new Color3D(cPtr, false);
      return ret;
    } 
  }

  public float AngleInnerCone {
    set {
      AssimpPINVOKE.Light_AngleInnerCone_set(swigCPtr, value);
    } 
    get {
      float ret = AssimpPINVOKE.Light_AngleInnerCone_get(swigCPtr);
      return ret;
    } 
  }

  public float AngleOuterCone {
    set {
      AssimpPINVOKE.Light_AngleOuterCone_set(swigCPtr, value);
    } 
    get {
      float ret = AssimpPINVOKE.Light_AngleOuterCone_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_aiVector2tT_float_t Size {
    set {
      AssimpPINVOKE.Light_Size_set(swigCPtr, SWIGTYPE_p_aiVector2tT_float_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Light_Size_get(swigCPtr);
      SWIGTYPE_p_aiVector2tT_float_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_aiVector2tT_float_t(cPtr, false);
      return ret;
    } 
  }

  public Light() : this(AssimpPINVOKE.new_Light(), true) {
  }

}

}
