//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public enum LightSourceType {
  LightSource_UNDEFINED = 0x0,
  LightSource_DIRECTIONAL = 0x1,
  LightSource_POINT = 0x2,
  LightSource_SPOT = 0x3,
  LightSource_AMBIENT = 0x4,
  LightSource_AREA = 0x5
}

}
