//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public class Node : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Node(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Node obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Node obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Node() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AssimpPINVOKE.delete_Node(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public String Name {
    set {
      AssimpPINVOKE.Node_Name_set(swigCPtr, String.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Node_Name_get(swigCPtr);
      String ret = (cPtr == global::System.IntPtr.Zero) ? null : new String(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_aiMatrix4x4tT_float_t Transformation {
    set {
      AssimpPINVOKE.Node_Transformation_set(swigCPtr, SWIGTYPE_p_aiMatrix4x4tT_float_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Node_Transformation_get(swigCPtr);
      SWIGTYPE_p_aiMatrix4x4tT_float_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_aiMatrix4x4tT_float_t(cPtr, false);
      return ret;
    } 
  }

  public Node Parent {
    set {
      AssimpPINVOKE.Node_Parent_set(swigCPtr, Node.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Node_Parent_get(swigCPtr);
      Node ret = (cPtr == global::System.IntPtr.Zero) ? null : new Node(cPtr, false);
      return ret;
    } 
  }

  public uint NumChildren {
    set {
      AssimpPINVOKE.Node_NumChildren_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.Node_NumChildren_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_p_aiNode Children {
    set {
      AssimpPINVOKE.Node_Children_set(swigCPtr, SWIGTYPE_p_p_aiNode.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Node_Children_get(swigCPtr);
      SWIGTYPE_p_p_aiNode ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_aiNode(cPtr, false);
      return ret;
    } 
  }

  public uint NumMeshes {
    set {
      AssimpPINVOKE.Node_NumMeshes_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.Node_NumMeshes_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_unsigned_int Meshes {
    set {
      AssimpPINVOKE.Node_Meshes_set(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Node_Meshes_get(swigCPtr);
      SWIGTYPE_p_unsigned_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
      return ret;
    } 
  }

  public Metadata MetaData {
    set {
      AssimpPINVOKE.Node_MetaData_set(swigCPtr, Metadata.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Node_MetaData_get(swigCPtr);
      Metadata ret = (cPtr == global::System.IntPtr.Zero) ? null : new Metadata(cPtr, false);
      return ret;
    } 
  }

  public Node() : this(AssimpPINVOKE.new_Node__SWIG_0(), true) {
  }

  public Node(SWIGTYPE_p_std__string name) : this(AssimpPINVOKE.new_Node__SWIG_1(SWIGTYPE_p_std__string.getCPtr(name)), true) {
    if (AssimpPINVOKE.SWIGPendingException.Pending) throw AssimpPINVOKE.SWIGPendingException.Retrieve();
  }

  public Node FindNode(String name) {
    global::System.IntPtr cPtr = AssimpPINVOKE.Node_FindNode__SWIG_0(swigCPtr, String.getCPtr(name));
    Node ret = (cPtr == global::System.IntPtr.Zero) ? null : new Node(cPtr, false);
    if (AssimpPINVOKE.SWIGPendingException.Pending) throw AssimpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Node FindNode(string name) {
    global::System.IntPtr cPtr = AssimpPINVOKE.Node_FindNode__SWIG_2(swigCPtr, name);
    Node ret = (cPtr == global::System.IntPtr.Zero) ? null : new Node(cPtr, false);
    return ret;
  }

  public Node findBoneNode(Bone bone) {
    global::System.IntPtr cPtr = AssimpPINVOKE.Node_findBoneNode(swigCPtr, Bone.getCPtr(bone));
    Node ret = (cPtr == global::System.IntPtr.Zero) ? null : new Node(cPtr, false);
    return ret;
  }

  public void addChildren(uint numChildren, SWIGTYPE_p_p_aiNode children) {
    AssimpPINVOKE.Node_addChildren(swigCPtr, numChildren, SWIGTYPE_p_p_aiNode.getCPtr(children));
  }

}

}
