//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public enum Origin {
  Origin_SET = 0x0,
  Origin_CUR = 0x1,
  Origin_END = 0x2,
  _AI_ORIGIN_ENFORCE_ENUM_SIZE = 0x7fffffff
}

}
