//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public enum PostProcessSteps {
  Process_CalcTangentSpace = 0x1,
  Process_JoinIdenticalVertices = 0x2,
  Process_MakeLeftHanded = 0x4,
  Process_Triangulate = 0x8,
  Process_RemoveComponent = 0x10,
  Process_GenNormals = 0x20,
  Process_GenSmoothNormals = 0x40,
  Process_SplitLargeMeshes = 0x80,
  Process_PreTransformVertices = 0x100,
  Process_LimitBoneWeights = 0x200,
  Process_ValidateDataStructure = 0x400,
  Process_ImproveCacheLocality = 0x800,
  Process_RemoveRedundantMaterials = 0x1000,
  Process_FixInfacingNormals = 0x2000,
  Process_PopulateArmatureData = 0x4000,
  Process_SortByPType = 0x8000,
  Process_FindDegenerates = 0x10000,
  Process_FindInvalidData = 0x20000,
  Process_GenUVCoords = 0x40000,
  Process_TransformUVCoords = 0x80000,
  Process_FindInstances = 0x100000,
  Process_OptimizeMeshes = 0x200000,
  Process_OptimizeGraph = 0x400000,
  Process_FlipUVs = 0x800000,
  Process_FlipWindingOrder = 0x1000000,
  Process_SplitByBoneCount = 0x2000000,
  Process_Debone = 0x4000000,
  Process_GlobalScale = 0x8000000,
  Process_EmbedTextures = 0x10000000,
  Process_ForceGenNormals = 0x20000000,
  Process_DropNormals = 0x40000000,
  Process_GenBoundingBoxes = 0x80000000
}

}
