//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public enum PrimitiveType {
  PrimitiveType_POINT = 0x1,
  PrimitiveType_LINE = 0x2,
  PrimitiveType_TRIANGLE = 0x4,
  PrimitiveType_POLYGON = 0x8,
  PrimitiveType_NGONEncodingFlag = 0x10
}

}
