//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public enum PropertyTypeInfo {
  PTI_Float = 0x1,
  PTI_Double = 0x2,
  PTI_String = 0x3,
  PTI_Integer = 0x4,
  PTI_Buffer = 0x5
}

}
