//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public enum ShadingMode {
  ShadingMode_Flat = 0x1,
  ShadingMode_Gouraud = 0x2,
  ShadingMode_Phong = 0x3,
  ShadingMode_Blinn = 0x4,
  ShadingMode_Toon = 0x5,
  ShadingMode_OrenNayar = 0x6,
  ShadingMode_Minnaert = 0x7,
  ShadingMode_CookTorrance = 0x8,
  ShadingMode_NoShading = 0x9,
  ShadingMode_Unlit = aiShadingMode_NoShading,
  ShadingMode_Fresnel = 0xa,
  ShadingMode_PBR_BRDF = 0xb
}

}
