//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public enum TextureOp {
  TextureOp_Multiply = 0x0,
  TextureOp_Add = 0x1,
  TextureOp_Subtract = 0x2,
  TextureOp_Divide = 0x3,
  TextureOp_SmoothAdd = 0x4,
  TextureOp_SignedAdd = 0x5
}

}
