//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public enum TextureMapping {
  TextureMapping_UV = 0x0,
  TextureMapping_SPHERE = 0x1,
  TextureMapping_CYLINDER = 0x2,
  TextureMapping_BOX = 0x3,
  TextureMapping_PLANE = 0x4,
  TextureMapping_OTHER = 0x5
}

}
