<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <LibVersion>6.0.5.0-rc1</LibVersion> 
    <NuGetPathUnix Condition="'$(MSBuildRuntimeType)' == 'Core' AND '$(OS)' != 'Windows_NT'">$(NuGetPackageRoot.Replace('\',
      '/'))</NuGetPathUnix>
    <NuGetPathUnix Condition="'$(NuGetPathUnix)' == ''">$(NuGetPackageRoot)</NuGetPathUnix>
    <IsWin Condition="$(RuntimeIdentifier.StartsWith('win'))">true</IsWin>
    <IsWin Condition="'$(IsWin)' == ''">false</IsWin>
  </PropertyGroup>
 
  <!-- Android Native Libraries -->
  <ItemGroup Condition="$(TargetFramework.Contains('android'))">
    <!-- armeabi-v7a -->
    <AndroidNativeLibrary Include="$(NuGetPathUnix)Assimp.Maui/$(LibVersion)/runtimes/android-arm/native/*.so">
      <Abi>armeabi-v7a</Abi>
      <Link>Platforms/Android/lib/armeabi-v7a/%(Filename)%(Extension)</Link>
    </AndroidNativeLibrary>

    <!-- arm64-v8a -->
    <AndroidNativeLibrary Include="$(NuGetPathUnix)Assimp.Maui/$(LibVersion)/runtimes/android-arm64/native/*.so">
      <Abi>arm64-v8a</Abi>
      <Link>Platforms/Android/lib/arm64-v8a/%(Filename)%(Extension)</Link>
    </AndroidNativeLibrary>

    <!-- x86 -->
    <AndroidNativeLibrary Include="$(NuGetPathUnix)Assimp.Maui/$(LibVersion)/runtimes/android-x86/native/*.so">
      <Abi>x86</Abi>
      <Link>Platforms/Android/lib/x86/%(Filename)%(Extension)</Link>
    </AndroidNativeLibrary>

    <!-- x86_64 -->
    <AndroidNativeLibrary Include="$(NuGetPathUnix)Assimp.Maui/$(LibVersion)/runtimes/android-x86_64/native/*.so">
      <Abi>x86_64</Abi>
      <Link>Platforms/Android/lib/x86_64/%(Filename)%(Extension)</Link>
    </AndroidNativeLibrary>
  </ItemGroup>

  <!-- iOS Static Libraries -->
  <ItemGroup Condition="$(RuntimeIdentifier.StartsWith('ios'))">
    <None Include="$(NuGetPathUnix)Assimp.Maui/$(LibVersion)/runtimes/ios-arm64/native/*.a">
      <Link>Platforms/iOS/lib/arm64/libassimp.a</Link>
      <Visible>True</Visible>
    </None>
    <None Include="$(NuGetPathUnix)Assimp.Maui/$(LibVersion)/runtimes/iossimulator-arm64/native/*.a">
      <Link>Platforms/iOS/lib/arm64s/libassimp.a</Link>
      <Visible>True</Visible>
    </None>
    <None Include="$(NuGetPathUnix)Assimp.Maui/$(LibVersion)/runtimes/iossimulator-x64/native/*.a">
      <Link>Platforms/iOS/lib/x86_64/libassimp.a</Link>
      <Visible>True</Visible>
    </None>
  </ItemGroup>

  <!-- iOS Native Linking -->
  <ItemGroup Condition="$(RuntimeIdentifier.StartsWith('iossimulator-x64'))">
    <NativeReference
      Include="$(NuGetPathUnix)Assimp.Maui/$(LibVersion)/runtimes/iossimulator-x64/native/libassimp.a">
      <Kind>Static</Kind>
      <ForceLoad>True</ForceLoad>
      <SmartLink>False</SmartLink>
    </NativeReference>
  </ItemGroup>

  <ItemGroup Condition="$(RuntimeIdentifier.StartsWith('iossimulator-arm64'))">
    <NativeReference
      Include="$(NuGetPathUnix)Assimp.Maui/$(LibVersion)/runtimes/iossimulator-arm64/native/libassimp.a">
      <Kind>Static</Kind>
      <ForceLoad>True</ForceLoad>
      <SmartLink>False</SmartLink>
    </NativeReference>
  </ItemGroup>

  <ItemGroup Condition="$(RuntimeIdentifier.StartsWith('ios-arm64'))">
    <NativeReference
      Include="$(NuGetPathUnix)Assimp.Maui/$(LibVersion)/runtimes/ios-arm64/native/libassimp.a">
      <Kind>Static</Kind>
      <ForceLoad>True</ForceLoad>
      <SmartLink>False</SmartLink>
    </NativeReference>
  </ItemGroup>

  <!-- MacOSX Native Linking -->
  <ItemGroup Condition="$(RuntimeIdentifier.StartsWith('maccatalyst-arm64'))">
    <NativeReference
      Include="$(NuGetPathUnix)Assimp.Maui/$(LibVersion)/runtimes/maccatalyst-arm64/native/libassimp.a">
      <Kind>Static</Kind>
      <ForceLoad>True</ForceLoad>
      <SmartLink>False</SmartLink>
    </NativeReference>
  </ItemGroup>

  <ItemGroup Condition="$(RuntimeIdentifier.StartsWith('maccatalyst-x86_64'))">
    <NativeReference
      Include="$(NuGetPathUnix)Assimp.Maui/$(LibVersion)/runtimes/maccatalyst-x64/native/libassimp.a">
      <Kind>Static</Kind>
      <ForceLoad>True</ForceLoad>
      <SmartLink>False</SmartLink>
    </NativeReference>
  </ItemGroup>

  <!-- Windows Native Linking -->
  <ItemGroup Condition="'$(IsWin)' == 'true'">
    <None Condition="$(RuntimeIdentifier.Contains('x64')) Or '$(Platform)' == 'x64'"
        Include="$(NuGetPackageRoot)Assimp.Maui\$(LibVersion)\runtimes\win-x64\native\assimp_maui.dll">
      <Link>Platforms\Windows\Native\x64\%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>False</Visible>
      <TargetPath>%(Filename)%(Extension)</TargetPath>
    </None>

    <None Condition="$(RuntimeIdentifier.Contains('x64')) Or '$(Platform)' == 'x64'"
        Include="$(NuGetPackageRoot)Assimp.Maui\$(LibVersion)\runtimes\win-x64\native\assimp-vc143-mt.dll">
      <Link>Platforms\Windows\Native\x64\%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>False</Visible>
      <TargetPath>%(Filename)%(Extension)</TargetPath>
    </None>

    <None Condition="$(RuntimeIdentifier.Contains('arm64')) Or '$(Platform)' == 'ARM64' Or '$(Platform)' == 'arm64'"
        Include="$(NuGetPackageRoot)Assimp.Maui\$(LibVersion)\runtimes\win-arm64\native\assimp_maui.dll">
      <Link>Platforms\Windows\Native\ARM64\%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <Visible>False</Visible>
      <TargetPath>%(Filename)%(Extension)</TargetPath>
    </None>

    <None Condition="$(RuntimeIdentifier.Contains('arm64')) Or '$(Platform)' == 'ARM64' Or '$(Platform)' == 'arm64'"
        Include="$(NuGetPackageRoot)Assimp.Maui\$(LibVersion)\runtimes\win-arm64\native\assimp-vc143-mt.dll">
      <Link>Platforms\Windows\Native\ARM64\%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <Visible>False</Visible>
      <TargetPath>%(Filename)%(Extension)</TargetPath>
    </None>
  </ItemGroup>
</Project>