//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public enum PostProcessSteps {
  Process_CalcTangentSpace = 1,
  Process_JoinIdenticalVertices = 2,
  Process_MakeLeftHanded = 4,
  Process_Triangulate = 8,
  Process_RemoveComponent = 16,
  Process_GenNormals = 32,
  Process_GenSmoothNormals = 64,
  Process_SplitLargeMeshes = 128,
  Process_PreTransformVertices = 256,
  Process_LimitBoneWeights = 512,
  Process_ValidateDataStructure = 1024,
  Process_ImproveCacheLocality = 2048,
  Process_RemoveRedundantMaterials = 4096,
  Process_FixInfacingNormals = 8192,
  Process_PopulateArmatureData = 16384,
  Process_SortByPType = 32768,
  Process_FindDegenerates = 65536,
  Process_FindInvalidData = 131072,
  Process_GenUVCoords = 262144,
  Process_TransformUVCoords = 524288,
  Process_FindInstances = 1048576,
  Process_OptimizeMeshes = 2097152,
  Process_OptimizeGraph = 4194304,
  Process_FlipUVs = 8388608,
  Process_FlipWindingOrder = 16777216,
  Process_SplitByBoneCount = 33554432,
  Process_Debone = 67108864,
  Process_GlobalScale = 134217728,
  Process_EmbedTextures = 268435456,
  Process_ForceGenNormals = 536870912,
  Process_DropNormals = 1073741824,
  Process_GenBoundingBoxes = 2147483648
}

}
