//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public enum TextureOp {
  TextureOp_Multiply = 0,
  TextureOp_Add = 1,
  TextureOp_Subtract = 2,
  TextureOp_Divide = 3,
  TextureOp_SmoothAdd = 4,
  TextureOp_SignedAdd = 5
}

}
