//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public class UVTransform : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal UVTransform(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(UVTransform obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(UVTransform obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~UVTransform() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AssimpPINVOKE.delete_UVTransform(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public SWIGTYPE_p_aiVector2tT_float_t Translation {
    set {
      AssimpPINVOKE.UVTransform_Translation_set(swigCPtr, SWIGTYPE_p_aiVector2tT_float_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.UVTransform_Translation_get(swigCPtr);
      SWIGTYPE_p_aiVector2tT_float_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_aiVector2tT_float_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_aiVector2tT_float_t Scaling {
    set {
      AssimpPINVOKE.UVTransform_Scaling_set(swigCPtr, SWIGTYPE_p_aiVector2tT_float_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.UVTransform_Scaling_get(swigCPtr);
      SWIGTYPE_p_aiVector2tT_float_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_aiVector2tT_float_t(cPtr, false);
      return ret;
    } 
  }

  public float Rotation {
    set {
      AssimpPINVOKE.UVTransform_Rotation_set(swigCPtr, value);
    } 
    get {
      float ret = AssimpPINVOKE.UVTransform_Rotation_get(swigCPtr);
      return ret;
    } 
  }

  public UVTransform() : this(AssimpPINVOKE.new_UVTransform(), true) {
  }

}

}
