//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public class Assimp {
  public static float _epsilon {
    get {
      float ret = AssimpPINVOKE._epsilon_get();
      return ret;
    } 
  }

  public static uint AI_MAXLEN {
    get {
      uint ret = AssimpPINVOKE.AI_MAXLEN_get();
      return ret;
    } 
  }

  public static string TextureTypeToString(TextureType in_) {
    string ret = AssimpPINVOKE.TextureTypeToString((int)in_);
    return ret;
  }

  public static Return GetMaterialProperty(Material pMat, string pKey, uint type, uint index, SWIGTYPE_p_p_aiMaterialProperty pPropOut) {
    Return ret = (Return)AssimpPINVOKE.GetMaterialProperty(Material.getCPtr(pMat), pKey, type, index, SWIGTYPE_p_p_aiMaterialProperty.getCPtr(pPropOut));
    return ret;
  }

  public static Return GetMaterialFloatArray(Material pMat, string pKey, uint type, uint index, SWIGTYPE_p_float pOut, SWIGTYPE_p_unsigned_int pMax) {
    Return ret = (Return)AssimpPINVOKE.GetMaterialFloatArray(Material.getCPtr(pMat), pKey, type, index, SWIGTYPE_p_float.getCPtr(pOut), SWIGTYPE_p_unsigned_int.getCPtr(pMax));
    return ret;
  }

  public static Return GetMaterialFloat(Material pMat, string pKey, uint type, uint index, SWIGTYPE_p_float pOut) {
    Return ret = (Return)AssimpPINVOKE.GetMaterialFloat(Material.getCPtr(pMat), pKey, type, index, SWIGTYPE_p_float.getCPtr(pOut));
    return ret;
  }

  public static Return GetMaterialIntegerArray(Material pMat, string pKey, uint type, uint index, SWIGTYPE_p_int pOut, SWIGTYPE_p_unsigned_int pMax) {
    Return ret = (Return)AssimpPINVOKE.GetMaterialIntegerArray(Material.getCPtr(pMat), pKey, type, index, SWIGTYPE_p_int.getCPtr(pOut), SWIGTYPE_p_unsigned_int.getCPtr(pMax));
    return ret;
  }

  public static Return GetMaterialInteger(Material pMat, string pKey, uint type, uint index, SWIGTYPE_p_int pOut) {
    Return ret = (Return)AssimpPINVOKE.GetMaterialInteger(Material.getCPtr(pMat), pKey, type, index, SWIGTYPE_p_int.getCPtr(pOut));
    return ret;
  }

  public static Return GetMaterialColor(Material pMat, string pKey, uint type, uint index, SWIGTYPE_p_aiColor4tT_float_t pOut) {
    Return ret = (Return)AssimpPINVOKE.GetMaterialColor(Material.getCPtr(pMat), pKey, type, index, SWIGTYPE_p_aiColor4tT_float_t.getCPtr(pOut));
    return ret;
  }

  public static Return GetMaterialUVTransform(Material pMat, string pKey, uint type, uint index, UVTransform pOut) {
    Return ret = (Return)AssimpPINVOKE.GetMaterialUVTransform(Material.getCPtr(pMat), pKey, type, index, UVTransform.getCPtr(pOut));
    return ret;
  }

  public static Return GetMaterialString(Material pMat, string pKey, uint type, uint index, String pOut) {
    Return ret = (Return)AssimpPINVOKE.GetMaterialString(Material.getCPtr(pMat), pKey, type, index, String.getCPtr(pOut));
    return ret;
  }

  public static uint GetMaterialTextureCount(Material pMat, TextureType type) {
    uint ret = AssimpPINVOKE.GetMaterialTextureCount(Material.getCPtr(pMat), (int)type);
    return ret;
  }

  public static Return GetMaterialTexture(Material mat, TextureType type, uint index, String path, SWIGTYPE_p_aiTextureMapping mapping, SWIGTYPE_p_unsigned_int uvindex, SWIGTYPE_p_float blend, SWIGTYPE_p_aiTextureOp op, SWIGTYPE_p_aiTextureMapMode mapmode, SWIGTYPE_p_unsigned_int flags) {
    Return ret = (Return)AssimpPINVOKE.GetMaterialTexture(Material.getCPtr(mat), (int)type, index, String.getCPtr(path), SWIGTYPE_p_aiTextureMapping.getCPtr(mapping), SWIGTYPE_p_unsigned_int.getCPtr(uvindex), SWIGTYPE_p_float.getCPtr(blend), SWIGTYPE_p_aiTextureOp.getCPtr(op), SWIGTYPE_p_aiTextureMapMode.getCPtr(mapmode), SWIGTYPE_p_unsigned_int.getCPtr(flags));
    return ret;
  }

  public static bool CompareKeys(Metadata lhs, Metadata rhs) {
    bool ret = AssimpPINVOKE.CompareKeys(Metadata.getCPtr(lhs), Metadata.getCPtr(rhs));
    if (AssimpPINVOKE.SWIGPendingException.Pending) throw AssimpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool CompareValues(Metadata lhs, Metadata rhs) {
    bool ret = AssimpPINVOKE.CompareValues(Metadata.getCPtr(lhs), Metadata.getCPtr(rhs));
    if (AssimpPINVOKE.SWIGPendingException.Pending) throw AssimpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static Scene ImportFile(string pFile, uint pFlags) {
    global::System.IntPtr cPtr = AssimpPINVOKE.ImportFile(pFile, pFlags);
    Scene ret = (cPtr == global::System.IntPtr.Zero) ? null : new Scene(cPtr, false);
    return ret;
  }

  public static Scene ImportFileEx(string pFile, uint pFlags, FileIO pFS) {
    global::System.IntPtr cPtr = AssimpPINVOKE.ImportFileEx(pFile, pFlags, FileIO.getCPtr(pFS));
    Scene ret = (cPtr == global::System.IntPtr.Zero) ? null : new Scene(cPtr, false);
    return ret;
  }

  public static Scene ImportFileExWithProperties(string pFile, uint pFlags, FileIO pFS, PropertyStore pProps) {
    global::System.IntPtr cPtr = AssimpPINVOKE.ImportFileExWithProperties(pFile, pFlags, FileIO.getCPtr(pFS), PropertyStore.getCPtr(pProps));
    Scene ret = (cPtr == global::System.IntPtr.Zero) ? null : new Scene(cPtr, false);
    return ret;
  }

  public static Scene ImportFileFromMemory(string pBuffer, uint pLength, uint pFlags, string pHint) {
    global::System.IntPtr cPtr = AssimpPINVOKE.ImportFileFromMemory(pBuffer, pLength, pFlags, pHint);
    Scene ret = (cPtr == global::System.IntPtr.Zero) ? null : new Scene(cPtr, false);
    return ret;
  }

  public static Scene ImportFileFromMemoryWithProperties(string pBuffer, uint pLength, uint pFlags, string pHint, PropertyStore pProps) {
    global::System.IntPtr cPtr = AssimpPINVOKE.ImportFileFromMemoryWithProperties(pBuffer, pLength, pFlags, pHint, PropertyStore.getCPtr(pProps));
    Scene ret = (cPtr == global::System.IntPtr.Zero) ? null : new Scene(cPtr, false);
    return ret;
  }

  public static Scene ApplyPostProcessing(Scene pScene, uint pFlags) {
    global::System.IntPtr cPtr = AssimpPINVOKE.ApplyPostProcessing(Scene.getCPtr(pScene), pFlags);
    Scene ret = (cPtr == global::System.IntPtr.Zero) ? null : new Scene(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_aiLogStream GetPredefinedLogStream(DefaultLogStream pStreams, string file) {
    SWIGTYPE_p_aiLogStream ret = new SWIGTYPE_p_aiLogStream(AssimpPINVOKE.GetPredefinedLogStream((int)pStreams, file), true);
    return ret;
  }

  public static void AttachLogStream(SWIGTYPE_p_aiLogStream stream) {
    AssimpPINVOKE.AttachLogStream(SWIGTYPE_p_aiLogStream.getCPtr(stream));
  }

  public static void EnableVerboseLogging(int d) {
    AssimpPINVOKE.EnableVerboseLogging(d);
  }

  public static Return DetachLogStream(SWIGTYPE_p_aiLogStream stream) {
    Return ret = (Return)AssimpPINVOKE.DetachLogStream(SWIGTYPE_p_aiLogStream.getCPtr(stream));
    return ret;
  }

  public static void DetachAllLogStreams() {
    AssimpPINVOKE.DetachAllLogStreams();
  }

  public static void ReleaseImport(Scene pScene) {
    AssimpPINVOKE.ReleaseImport(Scene.getCPtr(pScene));
  }

  public static string GetErrorString() {
    string ret = AssimpPINVOKE.GetErrorString();
    return ret;
  }

  public static int IsExtensionSupported(string szExtension) {
    int ret = AssimpPINVOKE.IsExtensionSupported(szExtension);
    return ret;
  }

  public static void GetExtensionList(String szOut) {
    AssimpPINVOKE.GetExtensionList(String.getCPtr(szOut));
  }

  public static void GetMemoryRequirements(Scene pIn, MemoryInfo in_) {
    AssimpPINVOKE.GetMemoryRequirements(Scene.getCPtr(pIn), MemoryInfo.getCPtr(in_));
  }

  public static Texture GetEmbeddedTexture(Scene pIn, string filename) {
    global::System.IntPtr cPtr = AssimpPINVOKE.GetEmbeddedTexture(Scene.getCPtr(pIn), filename);
    Texture ret = (cPtr == global::System.IntPtr.Zero) ? null : new Texture(cPtr, false);
    return ret;
  }

  public static PropertyStore CreatePropertyStore() {
    global::System.IntPtr cPtr = AssimpPINVOKE.CreatePropertyStore();
    PropertyStore ret = (cPtr == global::System.IntPtr.Zero) ? null : new PropertyStore(cPtr, false);
    return ret;
  }

  public static void ReleasePropertyStore(PropertyStore p) {
    AssimpPINVOKE.ReleasePropertyStore(PropertyStore.getCPtr(p));
  }

  public static void SetImportPropertyInteger(PropertyStore store, string szName, int value) {
    AssimpPINVOKE.SetImportPropertyInteger(PropertyStore.getCPtr(store), szName, value);
  }

  public static void SetImportPropertyFloat(PropertyStore store, string szName, float value) {
    AssimpPINVOKE.SetImportPropertyFloat(PropertyStore.getCPtr(store), szName, value);
  }

  public static void SetImportPropertyString(PropertyStore store, string szName, String st) {
    AssimpPINVOKE.SetImportPropertyString(PropertyStore.getCPtr(store), szName, String.getCPtr(st));
  }

  public static void SetImportPropertyMatrix(PropertyStore store, string szName, SWIGTYPE_p_aiMatrix4x4tT_float_t mat) {
    AssimpPINVOKE.SetImportPropertyMatrix(PropertyStore.getCPtr(store), szName, SWIGTYPE_p_aiMatrix4x4tT_float_t.getCPtr(mat));
  }

  public static void CreateQuaternionFromMatrix(SWIGTYPE_p_aiQuaterniontT_float_t quat, SWIGTYPE_p_aiMatrix3x3tT_float_t mat) {
    AssimpPINVOKE.CreateQuaternionFromMatrix(SWIGTYPE_p_aiQuaterniontT_float_t.getCPtr(quat), SWIGTYPE_p_aiMatrix3x3tT_float_t.getCPtr(mat));
  }

  public static void DecomposeMatrix(SWIGTYPE_p_aiMatrix4x4tT_float_t mat, SWIGTYPE_p_aiVector3tT_float_t scaling, SWIGTYPE_p_aiQuaterniontT_float_t rotation, SWIGTYPE_p_aiVector3tT_float_t position) {
    AssimpPINVOKE.DecomposeMatrix(SWIGTYPE_p_aiMatrix4x4tT_float_t.getCPtr(mat), SWIGTYPE_p_aiVector3tT_float_t.getCPtr(scaling), SWIGTYPE_p_aiQuaterniontT_float_t.getCPtr(rotation), SWIGTYPE_p_aiVector3tT_float_t.getCPtr(position));
  }

  public static void TransposeMatrix4(SWIGTYPE_p_aiMatrix4x4tT_float_t mat) {
    AssimpPINVOKE.TransposeMatrix4(SWIGTYPE_p_aiMatrix4x4tT_float_t.getCPtr(mat));
  }

  public static void TransposeMatrix3(SWIGTYPE_p_aiMatrix3x3tT_float_t mat) {
    AssimpPINVOKE.TransposeMatrix3(SWIGTYPE_p_aiMatrix3x3tT_float_t.getCPtr(mat));
  }

  public static void TransformVecByMatrix3(SWIGTYPE_p_aiVector3tT_float_t vec, SWIGTYPE_p_aiMatrix3x3tT_float_t mat) {
    AssimpPINVOKE.TransformVecByMatrix3(SWIGTYPE_p_aiVector3tT_float_t.getCPtr(vec), SWIGTYPE_p_aiMatrix3x3tT_float_t.getCPtr(mat));
  }

  public static void TransformVecByMatrix4(SWIGTYPE_p_aiVector3tT_float_t vec, SWIGTYPE_p_aiMatrix4x4tT_float_t mat) {
    AssimpPINVOKE.TransformVecByMatrix4(SWIGTYPE_p_aiVector3tT_float_t.getCPtr(vec), SWIGTYPE_p_aiMatrix4x4tT_float_t.getCPtr(mat));
  }

  public static void MultiplyMatrix4(SWIGTYPE_p_aiMatrix4x4tT_float_t dst, SWIGTYPE_p_aiMatrix4x4tT_float_t src) {
    AssimpPINVOKE.MultiplyMatrix4(SWIGTYPE_p_aiMatrix4x4tT_float_t.getCPtr(dst), SWIGTYPE_p_aiMatrix4x4tT_float_t.getCPtr(src));
  }

  public static void MultiplyMatrix3(SWIGTYPE_p_aiMatrix3x3tT_float_t dst, SWIGTYPE_p_aiMatrix3x3tT_float_t src) {
    AssimpPINVOKE.MultiplyMatrix3(SWIGTYPE_p_aiMatrix3x3tT_float_t.getCPtr(dst), SWIGTYPE_p_aiMatrix3x3tT_float_t.getCPtr(src));
  }

  public static void IdentityMatrix3(SWIGTYPE_p_aiMatrix3x3tT_float_t mat) {
    AssimpPINVOKE.IdentityMatrix3(SWIGTYPE_p_aiMatrix3x3tT_float_t.getCPtr(mat));
  }

  public static void IdentityMatrix4(SWIGTYPE_p_aiMatrix4x4tT_float_t mat) {
    AssimpPINVOKE.IdentityMatrix4(SWIGTYPE_p_aiMatrix4x4tT_float_t.getCPtr(mat));
  }

  public static uint GetImportFormatCount() {
    uint ret = AssimpPINVOKE.GetImportFormatCount();
    return ret;
  }

  public static SWIGTYPE_p_aiImporterDesc GetImportFormatDescription(uint pIndex) {
    global::System.IntPtr cPtr = AssimpPINVOKE.GetImportFormatDescription(pIndex);
    SWIGTYPE_p_aiImporterDesc ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_aiImporterDesc(cPtr, false);
    return ret;
  }

  public static int Vector2AreEqual(SWIGTYPE_p_aiVector2tT_float_t a, SWIGTYPE_p_aiVector2tT_float_t b) {
    int ret = AssimpPINVOKE.Vector2AreEqual(SWIGTYPE_p_aiVector2tT_float_t.getCPtr(a), SWIGTYPE_p_aiVector2tT_float_t.getCPtr(b));
    return ret;
  }

  public static int Vector2AreEqualEpsilon(SWIGTYPE_p_aiVector2tT_float_t a, SWIGTYPE_p_aiVector2tT_float_t b, float epsilon) {
    int ret = AssimpPINVOKE.Vector2AreEqualEpsilon(SWIGTYPE_p_aiVector2tT_float_t.getCPtr(a), SWIGTYPE_p_aiVector2tT_float_t.getCPtr(b), epsilon);
    return ret;
  }

  public static void Vector2Add(SWIGTYPE_p_aiVector2tT_float_t dst, SWIGTYPE_p_aiVector2tT_float_t src) {
    AssimpPINVOKE.Vector2Add(SWIGTYPE_p_aiVector2tT_float_t.getCPtr(dst), SWIGTYPE_p_aiVector2tT_float_t.getCPtr(src));
  }

  public static void Vector2Subtract(SWIGTYPE_p_aiVector2tT_float_t dst, SWIGTYPE_p_aiVector2tT_float_t src) {
    AssimpPINVOKE.Vector2Subtract(SWIGTYPE_p_aiVector2tT_float_t.getCPtr(dst), SWIGTYPE_p_aiVector2tT_float_t.getCPtr(src));
  }

  public static void Vector2Scale(SWIGTYPE_p_aiVector2tT_float_t dst, float s) {
    AssimpPINVOKE.Vector2Scale(SWIGTYPE_p_aiVector2tT_float_t.getCPtr(dst), s);
  }

  public static void Vector2SymMul(SWIGTYPE_p_aiVector2tT_float_t dst, SWIGTYPE_p_aiVector2tT_float_t other) {
    AssimpPINVOKE.Vector2SymMul(SWIGTYPE_p_aiVector2tT_float_t.getCPtr(dst), SWIGTYPE_p_aiVector2tT_float_t.getCPtr(other));
  }

  public static void Vector2DivideByScalar(SWIGTYPE_p_aiVector2tT_float_t dst, float s) {
    AssimpPINVOKE.Vector2DivideByScalar(SWIGTYPE_p_aiVector2tT_float_t.getCPtr(dst), s);
  }

  public static void Vector2DivideByVector(SWIGTYPE_p_aiVector2tT_float_t dst, SWIGTYPE_p_aiVector2tT_float_t v) {
    AssimpPINVOKE.Vector2DivideByVector(SWIGTYPE_p_aiVector2tT_float_t.getCPtr(dst), SWIGTYPE_p_aiVector2tT_float_t.getCPtr(v));
  }

  public static float Vector2Length(SWIGTYPE_p_aiVector2tT_float_t v) {
    float ret = AssimpPINVOKE.Vector2Length(SWIGTYPE_p_aiVector2tT_float_t.getCPtr(v));
    return ret;
  }

  public static float Vector2SquareLength(SWIGTYPE_p_aiVector2tT_float_t v) {
    float ret = AssimpPINVOKE.Vector2SquareLength(SWIGTYPE_p_aiVector2tT_float_t.getCPtr(v));
    return ret;
  }

  public static void Vector2Negate(SWIGTYPE_p_aiVector2tT_float_t dst) {
    AssimpPINVOKE.Vector2Negate(SWIGTYPE_p_aiVector2tT_float_t.getCPtr(dst));
  }

  public static float Vector2DotProduct(SWIGTYPE_p_aiVector2tT_float_t a, SWIGTYPE_p_aiVector2tT_float_t b) {
    float ret = AssimpPINVOKE.Vector2DotProduct(SWIGTYPE_p_aiVector2tT_float_t.getCPtr(a), SWIGTYPE_p_aiVector2tT_float_t.getCPtr(b));
    return ret;
  }

  public static void Vector2Normalize(SWIGTYPE_p_aiVector2tT_float_t v) {
    AssimpPINVOKE.Vector2Normalize(SWIGTYPE_p_aiVector2tT_float_t.getCPtr(v));
  }

  public static int Vector3AreEqual(SWIGTYPE_p_aiVector3tT_float_t a, SWIGTYPE_p_aiVector3tT_float_t b) {
    int ret = AssimpPINVOKE.Vector3AreEqual(SWIGTYPE_p_aiVector3tT_float_t.getCPtr(a), SWIGTYPE_p_aiVector3tT_float_t.getCPtr(b));
    return ret;
  }

  public static int Vector3AreEqualEpsilon(SWIGTYPE_p_aiVector3tT_float_t a, SWIGTYPE_p_aiVector3tT_float_t b, float epsilon) {
    int ret = AssimpPINVOKE.Vector3AreEqualEpsilon(SWIGTYPE_p_aiVector3tT_float_t.getCPtr(a), SWIGTYPE_p_aiVector3tT_float_t.getCPtr(b), epsilon);
    return ret;
  }

  public static int Vector3LessThan(SWIGTYPE_p_aiVector3tT_float_t a, SWIGTYPE_p_aiVector3tT_float_t b) {
    int ret = AssimpPINVOKE.Vector3LessThan(SWIGTYPE_p_aiVector3tT_float_t.getCPtr(a), SWIGTYPE_p_aiVector3tT_float_t.getCPtr(b));
    return ret;
  }

  public static void Vector3Add(SWIGTYPE_p_aiVector3tT_float_t dst, SWIGTYPE_p_aiVector3tT_float_t src) {
    AssimpPINVOKE.Vector3Add(SWIGTYPE_p_aiVector3tT_float_t.getCPtr(dst), SWIGTYPE_p_aiVector3tT_float_t.getCPtr(src));
  }

  public static void Vector3Subtract(SWIGTYPE_p_aiVector3tT_float_t dst, SWIGTYPE_p_aiVector3tT_float_t src) {
    AssimpPINVOKE.Vector3Subtract(SWIGTYPE_p_aiVector3tT_float_t.getCPtr(dst), SWIGTYPE_p_aiVector3tT_float_t.getCPtr(src));
  }

  public static void Vector3Scale(SWIGTYPE_p_aiVector3tT_float_t dst, float s) {
    AssimpPINVOKE.Vector3Scale(SWIGTYPE_p_aiVector3tT_float_t.getCPtr(dst), s);
  }

  public static void Vector3SymMul(SWIGTYPE_p_aiVector3tT_float_t dst, SWIGTYPE_p_aiVector3tT_float_t other) {
    AssimpPINVOKE.Vector3SymMul(SWIGTYPE_p_aiVector3tT_float_t.getCPtr(dst), SWIGTYPE_p_aiVector3tT_float_t.getCPtr(other));
  }

  public static void Vector3DivideByScalar(SWIGTYPE_p_aiVector3tT_float_t dst, float s) {
    AssimpPINVOKE.Vector3DivideByScalar(SWIGTYPE_p_aiVector3tT_float_t.getCPtr(dst), s);
  }

  public static void Vector3DivideByVector(SWIGTYPE_p_aiVector3tT_float_t dst, SWIGTYPE_p_aiVector3tT_float_t v) {
    AssimpPINVOKE.Vector3DivideByVector(SWIGTYPE_p_aiVector3tT_float_t.getCPtr(dst), SWIGTYPE_p_aiVector3tT_float_t.getCPtr(v));
  }

  public static float Vector3Length(SWIGTYPE_p_aiVector3tT_float_t v) {
    float ret = AssimpPINVOKE.Vector3Length(SWIGTYPE_p_aiVector3tT_float_t.getCPtr(v));
    return ret;
  }

  public static float Vector3SquareLength(SWIGTYPE_p_aiVector3tT_float_t v) {
    float ret = AssimpPINVOKE.Vector3SquareLength(SWIGTYPE_p_aiVector3tT_float_t.getCPtr(v));
    return ret;
  }

  public static void Vector3Negate(SWIGTYPE_p_aiVector3tT_float_t dst) {
    AssimpPINVOKE.Vector3Negate(SWIGTYPE_p_aiVector3tT_float_t.getCPtr(dst));
  }

  public static float Vector3DotProduct(SWIGTYPE_p_aiVector3tT_float_t a, SWIGTYPE_p_aiVector3tT_float_t b) {
    float ret = AssimpPINVOKE.Vector3DotProduct(SWIGTYPE_p_aiVector3tT_float_t.getCPtr(a), SWIGTYPE_p_aiVector3tT_float_t.getCPtr(b));
    return ret;
  }

  public static void Vector3CrossProduct(SWIGTYPE_p_aiVector3tT_float_t dst, SWIGTYPE_p_aiVector3tT_float_t a, SWIGTYPE_p_aiVector3tT_float_t b) {
    AssimpPINVOKE.Vector3CrossProduct(SWIGTYPE_p_aiVector3tT_float_t.getCPtr(dst), SWIGTYPE_p_aiVector3tT_float_t.getCPtr(a), SWIGTYPE_p_aiVector3tT_float_t.getCPtr(b));
  }

  public static void Vector3Normalize(SWIGTYPE_p_aiVector3tT_float_t v) {
    AssimpPINVOKE.Vector3Normalize(SWIGTYPE_p_aiVector3tT_float_t.getCPtr(v));
  }

  public static void Vector3NormalizeSafe(SWIGTYPE_p_aiVector3tT_float_t v) {
    AssimpPINVOKE.Vector3NormalizeSafe(SWIGTYPE_p_aiVector3tT_float_t.getCPtr(v));
  }

  public static void Vector3RotateByQuaternion(SWIGTYPE_p_aiVector3tT_float_t v, SWIGTYPE_p_aiQuaterniontT_float_t q) {
    AssimpPINVOKE.Vector3RotateByQuaternion(SWIGTYPE_p_aiVector3tT_float_t.getCPtr(v), SWIGTYPE_p_aiQuaterniontT_float_t.getCPtr(q));
  }

  public static void Matrix3FromMatrix4(SWIGTYPE_p_aiMatrix3x3tT_float_t dst, SWIGTYPE_p_aiMatrix4x4tT_float_t mat) {
    AssimpPINVOKE.Matrix3FromMatrix4(SWIGTYPE_p_aiMatrix3x3tT_float_t.getCPtr(dst), SWIGTYPE_p_aiMatrix4x4tT_float_t.getCPtr(mat));
  }

  public static void Matrix3FromQuaternion(SWIGTYPE_p_aiMatrix3x3tT_float_t mat, SWIGTYPE_p_aiQuaterniontT_float_t q) {
    AssimpPINVOKE.Matrix3FromQuaternion(SWIGTYPE_p_aiMatrix3x3tT_float_t.getCPtr(mat), SWIGTYPE_p_aiQuaterniontT_float_t.getCPtr(q));
  }

  public static int Matrix3AreEqual(SWIGTYPE_p_aiMatrix3x3tT_float_t a, SWIGTYPE_p_aiMatrix3x3tT_float_t b) {
    int ret = AssimpPINVOKE.Matrix3AreEqual(SWIGTYPE_p_aiMatrix3x3tT_float_t.getCPtr(a), SWIGTYPE_p_aiMatrix3x3tT_float_t.getCPtr(b));
    return ret;
  }

  public static int Matrix3AreEqualEpsilon(SWIGTYPE_p_aiMatrix3x3tT_float_t a, SWIGTYPE_p_aiMatrix3x3tT_float_t b, float epsilon) {
    int ret = AssimpPINVOKE.Matrix3AreEqualEpsilon(SWIGTYPE_p_aiMatrix3x3tT_float_t.getCPtr(a), SWIGTYPE_p_aiMatrix3x3tT_float_t.getCPtr(b), epsilon);
    return ret;
  }

  public static void Matrix3Inverse(SWIGTYPE_p_aiMatrix3x3tT_float_t mat) {
    AssimpPINVOKE.Matrix3Inverse(SWIGTYPE_p_aiMatrix3x3tT_float_t.getCPtr(mat));
  }

  public static float Matrix3Determinant(SWIGTYPE_p_aiMatrix3x3tT_float_t mat) {
    float ret = AssimpPINVOKE.Matrix3Determinant(SWIGTYPE_p_aiMatrix3x3tT_float_t.getCPtr(mat));
    return ret;
  }

  public static void Matrix3RotationZ(SWIGTYPE_p_aiMatrix3x3tT_float_t mat, float angle) {
    AssimpPINVOKE.Matrix3RotationZ(SWIGTYPE_p_aiMatrix3x3tT_float_t.getCPtr(mat), angle);
  }

  public static void Matrix3FromRotationAroundAxis(SWIGTYPE_p_aiMatrix3x3tT_float_t mat, SWIGTYPE_p_aiVector3tT_float_t axis, float angle) {
    AssimpPINVOKE.Matrix3FromRotationAroundAxis(SWIGTYPE_p_aiMatrix3x3tT_float_t.getCPtr(mat), SWIGTYPE_p_aiVector3tT_float_t.getCPtr(axis), angle);
  }

  public static void Matrix3Translation(SWIGTYPE_p_aiMatrix3x3tT_float_t mat, SWIGTYPE_p_aiVector2tT_float_t translation) {
    AssimpPINVOKE.Matrix3Translation(SWIGTYPE_p_aiMatrix3x3tT_float_t.getCPtr(mat), SWIGTYPE_p_aiVector2tT_float_t.getCPtr(translation));
  }

  public static void Matrix3FromTo(SWIGTYPE_p_aiMatrix3x3tT_float_t mat, SWIGTYPE_p_aiVector3tT_float_t from, SWIGTYPE_p_aiVector3tT_float_t to) {
    AssimpPINVOKE.Matrix3FromTo(SWIGTYPE_p_aiMatrix3x3tT_float_t.getCPtr(mat), SWIGTYPE_p_aiVector3tT_float_t.getCPtr(from), SWIGTYPE_p_aiVector3tT_float_t.getCPtr(to));
  }

  public static void Matrix4FromMatrix3(SWIGTYPE_p_aiMatrix4x4tT_float_t dst, SWIGTYPE_p_aiMatrix3x3tT_float_t mat) {
    AssimpPINVOKE.Matrix4FromMatrix3(SWIGTYPE_p_aiMatrix4x4tT_float_t.getCPtr(dst), SWIGTYPE_p_aiMatrix3x3tT_float_t.getCPtr(mat));
  }

  public static void Matrix4FromScalingQuaternionPosition(SWIGTYPE_p_aiMatrix4x4tT_float_t mat, SWIGTYPE_p_aiVector3tT_float_t scaling, SWIGTYPE_p_aiQuaterniontT_float_t rotation, SWIGTYPE_p_aiVector3tT_float_t position) {
    AssimpPINVOKE.Matrix4FromScalingQuaternionPosition(SWIGTYPE_p_aiMatrix4x4tT_float_t.getCPtr(mat), SWIGTYPE_p_aiVector3tT_float_t.getCPtr(scaling), SWIGTYPE_p_aiQuaterniontT_float_t.getCPtr(rotation), SWIGTYPE_p_aiVector3tT_float_t.getCPtr(position));
  }

  public static void Matrix4Add(SWIGTYPE_p_aiMatrix4x4tT_float_t dst, SWIGTYPE_p_aiMatrix4x4tT_float_t src) {
    AssimpPINVOKE.Matrix4Add(SWIGTYPE_p_aiMatrix4x4tT_float_t.getCPtr(dst), SWIGTYPE_p_aiMatrix4x4tT_float_t.getCPtr(src));
  }

  public static int Matrix4AreEqual(SWIGTYPE_p_aiMatrix4x4tT_float_t a, SWIGTYPE_p_aiMatrix4x4tT_float_t b) {
    int ret = AssimpPINVOKE.Matrix4AreEqual(SWIGTYPE_p_aiMatrix4x4tT_float_t.getCPtr(a), SWIGTYPE_p_aiMatrix4x4tT_float_t.getCPtr(b));
    return ret;
  }

  public static int Matrix4AreEqualEpsilon(SWIGTYPE_p_aiMatrix4x4tT_float_t a, SWIGTYPE_p_aiMatrix4x4tT_float_t b, float epsilon) {
    int ret = AssimpPINVOKE.Matrix4AreEqualEpsilon(SWIGTYPE_p_aiMatrix4x4tT_float_t.getCPtr(a), SWIGTYPE_p_aiMatrix4x4tT_float_t.getCPtr(b), epsilon);
    return ret;
  }

  public static void Matrix4Inverse(SWIGTYPE_p_aiMatrix4x4tT_float_t mat) {
    AssimpPINVOKE.Matrix4Inverse(SWIGTYPE_p_aiMatrix4x4tT_float_t.getCPtr(mat));
  }

  public static float Matrix4Determinant(SWIGTYPE_p_aiMatrix4x4tT_float_t mat) {
    float ret = AssimpPINVOKE.Matrix4Determinant(SWIGTYPE_p_aiMatrix4x4tT_float_t.getCPtr(mat));
    return ret;
  }

  public static int Matrix4IsIdentity(SWIGTYPE_p_aiMatrix4x4tT_float_t mat) {
    int ret = AssimpPINVOKE.Matrix4IsIdentity(SWIGTYPE_p_aiMatrix4x4tT_float_t.getCPtr(mat));
    return ret;
  }

  public static void Matrix4DecomposeIntoScalingEulerAnglesPosition(SWIGTYPE_p_aiMatrix4x4tT_float_t mat, SWIGTYPE_p_aiVector3tT_float_t scaling, SWIGTYPE_p_aiVector3tT_float_t rotation, SWIGTYPE_p_aiVector3tT_float_t position) {
    AssimpPINVOKE.Matrix4DecomposeIntoScalingEulerAnglesPosition(SWIGTYPE_p_aiMatrix4x4tT_float_t.getCPtr(mat), SWIGTYPE_p_aiVector3tT_float_t.getCPtr(scaling), SWIGTYPE_p_aiVector3tT_float_t.getCPtr(rotation), SWIGTYPE_p_aiVector3tT_float_t.getCPtr(position));
  }

  public static void Matrix4DecomposeIntoScalingAxisAnglePosition(SWIGTYPE_p_aiMatrix4x4tT_float_t mat, SWIGTYPE_p_aiVector3tT_float_t scaling, SWIGTYPE_p_aiVector3tT_float_t axis, SWIGTYPE_p_float angle, SWIGTYPE_p_aiVector3tT_float_t position) {
    AssimpPINVOKE.Matrix4DecomposeIntoScalingAxisAnglePosition(SWIGTYPE_p_aiMatrix4x4tT_float_t.getCPtr(mat), SWIGTYPE_p_aiVector3tT_float_t.getCPtr(scaling), SWIGTYPE_p_aiVector3tT_float_t.getCPtr(axis), SWIGTYPE_p_float.getCPtr(angle), SWIGTYPE_p_aiVector3tT_float_t.getCPtr(position));
  }

  public static void Matrix4DecomposeNoScaling(SWIGTYPE_p_aiMatrix4x4tT_float_t mat, SWIGTYPE_p_aiQuaterniontT_float_t rotation, SWIGTYPE_p_aiVector3tT_float_t position) {
    AssimpPINVOKE.Matrix4DecomposeNoScaling(SWIGTYPE_p_aiMatrix4x4tT_float_t.getCPtr(mat), SWIGTYPE_p_aiQuaterniontT_float_t.getCPtr(rotation), SWIGTYPE_p_aiVector3tT_float_t.getCPtr(position));
  }

  public static void Matrix4FromEulerAngles(SWIGTYPE_p_aiMatrix4x4tT_float_t mat, float x, float y, float z) {
    AssimpPINVOKE.Matrix4FromEulerAngles(SWIGTYPE_p_aiMatrix4x4tT_float_t.getCPtr(mat), x, y, z);
  }

  public static void Matrix4RotationX(SWIGTYPE_p_aiMatrix4x4tT_float_t mat, float angle) {
    AssimpPINVOKE.Matrix4RotationX(SWIGTYPE_p_aiMatrix4x4tT_float_t.getCPtr(mat), angle);
  }

  public static void Matrix4RotationY(SWIGTYPE_p_aiMatrix4x4tT_float_t mat, float angle) {
    AssimpPINVOKE.Matrix4RotationY(SWIGTYPE_p_aiMatrix4x4tT_float_t.getCPtr(mat), angle);
  }

  public static void Matrix4RotationZ(SWIGTYPE_p_aiMatrix4x4tT_float_t mat, float angle) {
    AssimpPINVOKE.Matrix4RotationZ(SWIGTYPE_p_aiMatrix4x4tT_float_t.getCPtr(mat), angle);
  }

  public static void Matrix4FromRotationAroundAxis(SWIGTYPE_p_aiMatrix4x4tT_float_t mat, SWIGTYPE_p_aiVector3tT_float_t axis, float angle) {
    AssimpPINVOKE.Matrix4FromRotationAroundAxis(SWIGTYPE_p_aiMatrix4x4tT_float_t.getCPtr(mat), SWIGTYPE_p_aiVector3tT_float_t.getCPtr(axis), angle);
  }

  public static void Matrix4Translation(SWIGTYPE_p_aiMatrix4x4tT_float_t mat, SWIGTYPE_p_aiVector3tT_float_t translation) {
    AssimpPINVOKE.Matrix4Translation(SWIGTYPE_p_aiMatrix4x4tT_float_t.getCPtr(mat), SWIGTYPE_p_aiVector3tT_float_t.getCPtr(translation));
  }

  public static void Matrix4Scaling(SWIGTYPE_p_aiMatrix4x4tT_float_t mat, SWIGTYPE_p_aiVector3tT_float_t scaling) {
    AssimpPINVOKE.Matrix4Scaling(SWIGTYPE_p_aiMatrix4x4tT_float_t.getCPtr(mat), SWIGTYPE_p_aiVector3tT_float_t.getCPtr(scaling));
  }

  public static void Matrix4FromTo(SWIGTYPE_p_aiMatrix4x4tT_float_t mat, SWIGTYPE_p_aiVector3tT_float_t from, SWIGTYPE_p_aiVector3tT_float_t to) {
    AssimpPINVOKE.Matrix4FromTo(SWIGTYPE_p_aiMatrix4x4tT_float_t.getCPtr(mat), SWIGTYPE_p_aiVector3tT_float_t.getCPtr(from), SWIGTYPE_p_aiVector3tT_float_t.getCPtr(to));
  }

  public static void QuaternionFromEulerAngles(SWIGTYPE_p_aiQuaterniontT_float_t q, float x, float y, float z) {
    AssimpPINVOKE.QuaternionFromEulerAngles(SWIGTYPE_p_aiQuaterniontT_float_t.getCPtr(q), x, y, z);
  }

  public static void QuaternionFromAxisAngle(SWIGTYPE_p_aiQuaterniontT_float_t q, SWIGTYPE_p_aiVector3tT_float_t axis, float angle) {
    AssimpPINVOKE.QuaternionFromAxisAngle(SWIGTYPE_p_aiQuaterniontT_float_t.getCPtr(q), SWIGTYPE_p_aiVector3tT_float_t.getCPtr(axis), angle);
  }

  public static void QuaternionFromNormalizedQuaternion(SWIGTYPE_p_aiQuaterniontT_float_t q, SWIGTYPE_p_aiVector3tT_float_t normalized) {
    AssimpPINVOKE.QuaternionFromNormalizedQuaternion(SWIGTYPE_p_aiQuaterniontT_float_t.getCPtr(q), SWIGTYPE_p_aiVector3tT_float_t.getCPtr(normalized));
  }

  public static int QuaternionAreEqual(SWIGTYPE_p_aiQuaterniontT_float_t a, SWIGTYPE_p_aiQuaterniontT_float_t b) {
    int ret = AssimpPINVOKE.QuaternionAreEqual(SWIGTYPE_p_aiQuaterniontT_float_t.getCPtr(a), SWIGTYPE_p_aiQuaterniontT_float_t.getCPtr(b));
    return ret;
  }

  public static int QuaternionAreEqualEpsilon(SWIGTYPE_p_aiQuaterniontT_float_t a, SWIGTYPE_p_aiQuaterniontT_float_t b, float epsilon) {
    int ret = AssimpPINVOKE.QuaternionAreEqualEpsilon(SWIGTYPE_p_aiQuaterniontT_float_t.getCPtr(a), SWIGTYPE_p_aiQuaterniontT_float_t.getCPtr(b), epsilon);
    return ret;
  }

  public static void QuaternionNormalize(SWIGTYPE_p_aiQuaterniontT_float_t q) {
    AssimpPINVOKE.QuaternionNormalize(SWIGTYPE_p_aiQuaterniontT_float_t.getCPtr(q));
  }

  public static void QuaternionConjugate(SWIGTYPE_p_aiQuaterniontT_float_t q) {
    AssimpPINVOKE.QuaternionConjugate(SWIGTYPE_p_aiQuaterniontT_float_t.getCPtr(q));
  }

  public static void QuaternionMultiply(SWIGTYPE_p_aiQuaterniontT_float_t dst, SWIGTYPE_p_aiQuaterniontT_float_t q) {
    AssimpPINVOKE.QuaternionMultiply(SWIGTYPE_p_aiQuaterniontT_float_t.getCPtr(dst), SWIGTYPE_p_aiQuaterniontT_float_t.getCPtr(q));
  }

  public static void QuaternionInterpolate(SWIGTYPE_p_aiQuaterniontT_float_t dst, SWIGTYPE_p_aiQuaterniontT_float_t start, SWIGTYPE_p_aiQuaterniontT_float_t end, float factor) {
    AssimpPINVOKE.QuaternionInterpolate(SWIGTYPE_p_aiQuaterniontT_float_t.getCPtr(dst), SWIGTYPE_p_aiQuaterniontT_float_t.getCPtr(start), SWIGTYPE_p_aiQuaterniontT_float_t.getCPtr(end), factor);
  }

  public static readonly int ASSIMP_AI_REAL_TEXT_PRECISION = AssimpPINVOKE.ASSIMP_AI_REAL_TEXT_PRECISION_get();
  public static readonly double AI_MATH_PI = AssimpPINVOKE.AI_MATH_PI_get();
  public static readonly double AI_MATH_TWO_PI = AssimpPINVOKE.AI_MATH_TWO_PI_get();
  public static readonly double AI_MATH_HALF_PI = AssimpPINVOKE.AI_MATH_HALF_PI_get();
  public static readonly float AI_MATH_PI_F = AssimpPINVOKE.AI_MATH_PI_F_get();
  public static readonly float AI_MATH_TWO_PI_F = AssimpPINVOKE.AI_MATH_TWO_PI_F_get();
  public static readonly float AI_MATH_HALF_PI_F = AssimpPINVOKE.AI_MATH_HALF_PI_F_get();
  public static readonly string AI_EMBEDDED_TEXNAME_PREFIX = AssimpPINVOKE.AI_EMBEDDED_TEXNAME_PREFIX_get();
  public static readonly int HINTMAXTEXTURELEN = AssimpPINVOKE.HINTMAXTEXTURELEN_get();
  public static readonly int AI_MAX_FACE_INDICES = AssimpPINVOKE.AI_MAX_FACE_INDICES_get();
  public static readonly int AI_MAX_BONE_WEIGHTS = AssimpPINVOKE.AI_MAX_BONE_WEIGHTS_get();
  public static readonly int AI_MAX_VERTICES = AssimpPINVOKE.AI_MAX_VERTICES_get();
  public static readonly int AI_MAX_FACES = AssimpPINVOKE.AI_MAX_FACES_get();
  public static readonly int AI_MAX_NUMBER_OF_COLOR_SETS = AssimpPINVOKE.AI_MAX_NUMBER_OF_COLOR_SETS_get();
  public static readonly int AI_MAX_NUMBER_OF_TEXTURECOORDS = AssimpPINVOKE.AI_MAX_NUMBER_OF_TEXTURECOORDS_get();
  public static readonly string AI_DEFAULT_MATERIAL_NAME = AssimpPINVOKE.AI_DEFAULT_MATERIAL_NAME_get();
  public static readonly string _AI_MATKEY_TEXTURE_BASE = AssimpPINVOKE._AI_MATKEY_TEXTURE_BASE_get();
  public static readonly string _AI_MATKEY_UVWSRC_BASE = AssimpPINVOKE._AI_MATKEY_UVWSRC_BASE_get();
  public static readonly string _AI_MATKEY_TEXOP_BASE = AssimpPINVOKE._AI_MATKEY_TEXOP_BASE_get();
  public static readonly string _AI_MATKEY_MAPPING_BASE = AssimpPINVOKE._AI_MATKEY_MAPPING_BASE_get();
  public static readonly string _AI_MATKEY_TEXBLEND_BASE = AssimpPINVOKE._AI_MATKEY_TEXBLEND_BASE_get();
  public static readonly string _AI_MATKEY_MAPPINGMODE_U_BASE = AssimpPINVOKE._AI_MATKEY_MAPPINGMODE_U_BASE_get();
  public static readonly string _AI_MATKEY_MAPPINGMODE_V_BASE = AssimpPINVOKE._AI_MATKEY_MAPPINGMODE_V_BASE_get();
  public static readonly string _AI_MATKEY_TEXMAP_AXIS_BASE = AssimpPINVOKE._AI_MATKEY_TEXMAP_AXIS_BASE_get();
  public static readonly string _AI_MATKEY_UVTRANSFORM_BASE = AssimpPINVOKE._AI_MATKEY_UVTRANSFORM_BASE_get();
  public static readonly string _AI_MATKEY_TEXFLAGS_BASE = AssimpPINVOKE._AI_MATKEY_TEXFLAGS_BASE_get();
  public static readonly int AI_SCENE_FLAGS_INCOMPLETE = AssimpPINVOKE.AI_SCENE_FLAGS_INCOMPLETE_get();
  public static readonly int AI_SCENE_FLAGS_VALIDATED = AssimpPINVOKE.AI_SCENE_FLAGS_VALIDATED_get();
  public static readonly int AI_SCENE_FLAGS_VALIDATION_WARNING = AssimpPINVOKE.AI_SCENE_FLAGS_VALIDATION_WARNING_get();
  public static readonly int AI_SCENE_FLAGS_NON_VERBOSE_FORMAT = AssimpPINVOKE.AI_SCENE_FLAGS_NON_VERBOSE_FORMAT_get();
  public static readonly int AI_SCENE_FLAGS_TERRAIN = AssimpPINVOKE.AI_SCENE_FLAGS_TERRAIN_get();
  public static readonly int AI_SCENE_FLAGS_ALLOW_SHARED = AssimpPINVOKE.AI_SCENE_FLAGS_ALLOW_SHARED_get();
  public static readonly int AI_FALSE = AssimpPINVOKE.AI_FALSE_get();
  public static readonly int AI_TRUE = AssimpPINVOKE.AI_TRUE_get();
}

}
