//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public class NodeAnim : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal NodeAnim(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(NodeAnim obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(NodeAnim obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~NodeAnim() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AssimpPINVOKE.delete_NodeAnim(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public String NodeName {
    set {
      AssimpPINVOKE.NodeAnim_NodeName_set(swigCPtr, String.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.NodeAnim_NodeName_get(swigCPtr);
      String ret = (cPtr == global::System.IntPtr.Zero) ? null : new String(cPtr, false);
      return ret;
    } 
  }

  public uint NumPositionKeys {
    set {
      AssimpPINVOKE.NodeAnim_NumPositionKeys_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.NodeAnim_NumPositionKeys_get(swigCPtr);
      return ret;
    } 
  }

  public VectorKey PositionKeys {
    set {
      AssimpPINVOKE.NodeAnim_PositionKeys_set(swigCPtr, VectorKey.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.NodeAnim_PositionKeys_get(swigCPtr);
      VectorKey ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorKey(cPtr, false);
      return ret;
    } 
  }

  public uint NumRotationKeys {
    set {
      AssimpPINVOKE.NodeAnim_NumRotationKeys_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.NodeAnim_NumRotationKeys_get(swigCPtr);
      return ret;
    } 
  }

  public QuatKey RotationKeys {
    set {
      AssimpPINVOKE.NodeAnim_RotationKeys_set(swigCPtr, QuatKey.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.NodeAnim_RotationKeys_get(swigCPtr);
      QuatKey ret = (cPtr == global::System.IntPtr.Zero) ? null : new QuatKey(cPtr, false);
      return ret;
    } 
  }

  public uint NumScalingKeys {
    set {
      AssimpPINVOKE.NodeAnim_NumScalingKeys_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.NodeAnim_NumScalingKeys_get(swigCPtr);
      return ret;
    } 
  }

  public VectorKey ScalingKeys {
    set {
      AssimpPINVOKE.NodeAnim_ScalingKeys_set(swigCPtr, VectorKey.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.NodeAnim_ScalingKeys_get(swigCPtr);
      VectorKey ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorKey(cPtr, false);
      return ret;
    } 
  }

  public AnimBehaviour PreState {
    set {
      AssimpPINVOKE.NodeAnim_PreState_set(swigCPtr, (int)value);
    } 
    get {
      AnimBehaviour ret = (AnimBehaviour)AssimpPINVOKE.NodeAnim_PreState_get(swigCPtr);
      return ret;
    } 
  }

  public AnimBehaviour PostState {
    set {
      AssimpPINVOKE.NodeAnim_PostState_set(swigCPtr, (int)value);
    } 
    get {
      AnimBehaviour ret = (AnimBehaviour)AssimpPINVOKE.NodeAnim_PostState_get(swigCPtr);
      return ret;
    } 
  }

  public NodeAnim() : this(AssimpPINVOKE.new_NodeAnim(), true) {
  }

}

}
