//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public enum ShadingMode {
  ShadingMode_Flat = 1,
  ShadingMode_Gouraud = 2,
  ShadingMode_Phong = 3,
  ShadingMode_Blinn = 4,
  ShadingMode_Toon = 5,
  ShadingMode_OrenNayar = 6,
  ShadingMode_Minnaert = 7,
  ShadingMode_CookTorrance = 8,
  ShadingMode_NoShading = 9,
  ShadingMode_Unlit = ShadingMode_NoShading,
  ShadingMode_Fresnel = 10,
  ShadingMode_PBR_BRDF = 11
}

}
