//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public class Bone : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Bone(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Bone obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Bone obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Bone() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AssimpPINVOKE.delete_Bone(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public String Name {
    set {
      AssimpPINVOKE.Bone_Name_set(swigCPtr, String.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Bone_Name_get(swigCPtr);
      String ret = (cPtr == global::System.IntPtr.Zero) ? null : new String(cPtr, false);
      return ret;
    } 
  }

  public uint NumWeights {
    set {
      AssimpPINVOKE.Bone_NumWeights_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.Bone_NumWeights_get(swigCPtr);
      return ret;
    } 
  }

  public Node Armature {
    set {
      AssimpPINVOKE.Bone_Armature_set(swigCPtr, Node.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Bone_Armature_get(swigCPtr);
      Node ret = (cPtr == global::System.IntPtr.Zero) ? null : new Node(cPtr, false);
      return ret;
    } 
  }

  public Node Node {
    set {
      AssimpPINVOKE.Bone_Node_set(swigCPtr, Node.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Bone_Node_get(swigCPtr);
      Node ret = (cPtr == global::System.IntPtr.Zero) ? null : new Node(cPtr, false);
      return ret;
    } 
  }

  public VertexWeight Weights {
    set {
      AssimpPINVOKE.Bone_Weights_set(swigCPtr, VertexWeight.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Bone_Weights_get(swigCPtr);
      VertexWeight ret = (cPtr == global::System.IntPtr.Zero) ? null : new VertexWeight(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_aiMatrix4x4tT_float_t OffsetMatrix {
    set {
      AssimpPINVOKE.Bone_OffsetMatrix_set(swigCPtr, SWIGTYPE_p_aiMatrix4x4tT_float_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Bone_OffsetMatrix_get(swigCPtr);
      SWIGTYPE_p_aiMatrix4x4tT_float_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_aiMatrix4x4tT_float_t(cPtr, false);
      return ret;
    } 
  }

  public Bone() : this(AssimpPINVOKE.new_Bone__SWIG_0(), true) {
  }

  public Bone(Bone other) : this(AssimpPINVOKE.new_Bone__SWIG_1(Bone.getCPtr(other)), true) {
    if (AssimpPINVOKE.SWIGPendingException.Pending) throw AssimpPINVOKE.SWIGPendingException.Retrieve();
  }

  public void copyVertexWeights(Bone other) {
    AssimpPINVOKE.Bone_copyVertexWeights(swigCPtr, Bone.getCPtr(other));
    if (AssimpPINVOKE.SWIGPendingException.Pending) throw AssimpPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
