//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public class Material : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Material(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Material obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Material obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Material() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AssimpPINVOKE.delete_Material(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Material() : this(AssimpPINVOKE.new_Material(), true) {
  }

  public String GetName() {
    String ret = new String(AssimpPINVOKE.Material_GetName(swigCPtr), true);
    return ret;
  }

  public uint GetTextureCount(TextureType type) {
    uint ret = AssimpPINVOKE.Material_GetTextureCount(swigCPtr, (int)type);
    return ret;
  }

  public SWIGTYPE_p_p_aiMaterialProperty Properties {
    set {
      AssimpPINVOKE.Material_Properties_set(swigCPtr, SWIGTYPE_p_p_aiMaterialProperty.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.Material_Properties_get(swigCPtr);
      SWIGTYPE_p_p_aiMaterialProperty ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_aiMaterialProperty(cPtr, false);
      return ret;
    } 
  }

  public uint NumProperties {
    set {
      AssimpPINVOKE.Material_NumProperties_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.Material_NumProperties_get(swigCPtr);
      return ret;
    } 
  }

  public uint NumAllocated {
    set {
      AssimpPINVOKE.Material_NumAllocated_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.Material_NumAllocated_get(swigCPtr);
      return ret;
    } 
  }

}

}
