//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public class MemoryInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MemoryInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MemoryInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(MemoryInfo obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~MemoryInfo() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AssimpPINVOKE.delete_MemoryInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public MemoryInfo() : this(AssimpPINVOKE.new_MemoryInfo(), true) {
  }

  public uint textures {
    set {
      AssimpPINVOKE.MemoryInfo_textures_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.MemoryInfo_textures_get(swigCPtr);
      return ret;
    } 
  }

  public uint materials {
    set {
      AssimpPINVOKE.MemoryInfo_materials_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.MemoryInfo_materials_get(swigCPtr);
      return ret;
    } 
  }

  public uint meshes {
    set {
      AssimpPINVOKE.MemoryInfo_meshes_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.MemoryInfo_meshes_get(swigCPtr);
      return ret;
    } 
  }

  public uint nodes {
    set {
      AssimpPINVOKE.MemoryInfo_nodes_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.MemoryInfo_nodes_get(swigCPtr);
      return ret;
    } 
  }

  public uint animations {
    set {
      AssimpPINVOKE.MemoryInfo_animations_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.MemoryInfo_animations_get(swigCPtr);
      return ret;
    } 
  }

  public uint cameras {
    set {
      AssimpPINVOKE.MemoryInfo_cameras_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.MemoryInfo_cameras_get(swigCPtr);
      return ret;
    } 
  }

  public uint lights {
    set {
      AssimpPINVOKE.MemoryInfo_lights_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.MemoryInfo_lights_get(swigCPtr);
      return ret;
    } 
  }

  public uint total {
    set {
      AssimpPINVOKE.MemoryInfo_total_set(swigCPtr, value);
    } 
    get {
      uint ret = AssimpPINVOKE.MemoryInfo_total_get(swigCPtr);
      return ret;
    } 
  }

}

}
