//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public enum MorphingMethod {
  MorphingMethod_UNKNOWN = 0x0,
  MorphingMethod_VERTEX_BLEND = 0x1,
  MorphingMethod_MORPH_NORMALIZED = 0x2,
  MorphingMethod_MORPH_RELATIVE = 0x3
}

}
