//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public class QuatKey : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal QuatKey(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(QuatKey obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(QuatKey obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~QuatKey() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AssimpPINVOKE.delete_QuatKey(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public double Time {
    set {
      AssimpPINVOKE.QuatKey_Time_set(swigCPtr, value);
    } 
    get {
      double ret = AssimpPINVOKE.QuatKey_Time_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_aiQuaterniontT_float_t Value {
    set {
      AssimpPINVOKE.QuatKey_Value_set(swigCPtr, SWIGTYPE_p_aiQuaterniontT_float_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AssimpPINVOKE.QuatKey_Value_get(swigCPtr);
      SWIGTYPE_p_aiQuaterniontT_float_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_aiQuaterniontT_float_t(cPtr, false);
      return ret;
    } 
  }

  public AnimInterpolation Interpolation {
    set {
      AssimpPINVOKE.QuatKey_Interpolation_set(swigCPtr, (int)value);
    } 
    get {
      AnimInterpolation ret = (AnimInterpolation)AssimpPINVOKE.QuatKey_Interpolation_get(swigCPtr);
      return ret;
    } 
  }

  public QuatKey() : this(AssimpPINVOKE.new_QuatKey__SWIG_0(), true) {
  }

  public QuatKey(double time, SWIGTYPE_p_aiQuaterniontT_float_t value) : this(AssimpPINVOKE.new_QuatKey__SWIG_1(time, SWIGTYPE_p_aiQuaterniontT_float_t.getCPtr(value)), true) {
    if (AssimpPINVOKE.SWIGPendingException.Pending) throw AssimpPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
