//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public enum Return {
  Return_SUCCESS = 0x0,
  Return_FAILURE = -0x1,
  Return_OUTOFMEMORY = -0x3,
  _AI_ENFORCE_ENUM_SIZE = 0x7fffffff
}

}
