//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public class Texel : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Texel(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Texel obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Texel obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Texel() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AssimpPINVOKE.delete_Texel(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public byte b {
    set {
      AssimpPINVOKE.Texel_b_set(swigCPtr, value);
    } 
    get {
      byte ret = AssimpPINVOKE.Texel_b_get(swigCPtr);
      return ret;
    } 
  }

  public byte g {
    set {
      AssimpPINVOKE.Texel_g_set(swigCPtr, value);
    } 
    get {
      byte ret = AssimpPINVOKE.Texel_g_get(swigCPtr);
      return ret;
    } 
  }

  public byte r {
    set {
      AssimpPINVOKE.Texel_r_set(swigCPtr, value);
    } 
    get {
      byte ret = AssimpPINVOKE.Texel_r_get(swigCPtr);
      return ret;
    } 
  }

  public byte a {
    set {
      AssimpPINVOKE.Texel_a_set(swigCPtr, value);
    } 
    get {
      byte ret = AssimpPINVOKE.Texel_a_get(swigCPtr);
      return ret;
    } 
  }

  public Texel() : this(AssimpPINVOKE.new_Texel(), true) {
  }

}

}
