//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Assimp.Maui {

public enum TextureType {
  TextureType_NONE = 0,
  TextureType_DIFFUSE = 1,
  TextureType_SPECULAR = 2,
  TextureType_AMBIENT = 3,
  TextureType_EMISSIVE = 4,
  TextureType_HEIGHT = 5,
  TextureType_NORMALS = 6,
  TextureType_SHININESS = 7,
  TextureType_OPACITY = 8,
  TextureType_DISPLACEMENT = 9,
  TextureType_LIGHTMAP = 10,
  TextureType_REFLECTION = 11,
  TextureType_BASE_COLOR = 12,
  TextureType_NORMAL_CAMERA = 13,
  TextureType_EMISSION_COLOR = 14,
  TextureType_METALNESS = 15,
  TextureType_DIFFUSE_ROUGHNESS = 16,
  TextureType_AMBIENT_OCCLUSION = 17,
  TextureType_UNKNOWN = 18,
  TextureType_SHEEN = 19,
  TextureType_CLEARCOAT = 20,
  TextureType_TRANSMISSION = 21,
  TextureType_MAYA_BASE = 22,
  TextureType_MAYA_SPECULAR = 23,
  TextureType_MAYA_SPECULAR_COLOR = 24,
  TextureType_MAYA_SPECULAR_ROUGHNESS = 25,
  TextureType_ANISOTROPY = 26,
  TextureType_GLTF_METALLIC_ROUGHNESS = 27
}

}
